/* Oniguruma amalgamation - single compilation unit */

#include "regcomp.c"
#include "regenc.c"
#include "regerror.c"
#include "regexec.c"
#include "regext.c"
#include "regparse.c"
#include "regsyntax.c"
#include "regtrav.c"
#include "regversion.c"
#include "st.c"
#include "onig_init.c"

/* Encodings */
#include "ascii.c"
#include "utf8.c"
#include "utf16_be.c"
#include "utf16_le.c"
#include "utf32_be.c"
#include "utf32_le.c"
#include "unicode.c"
#include "unicode_fold_data.c"
#include "unicode_fold1_key.c"
#include "unicode_fold2_key.c"
#include "unicode_fold3_key.c"
#include "unicode_unfold_key.c"
#include "unicode_property_data.c"
#include "unicode_property_data_posix.c"
#include "unicode_egcb_data.c"
#include "unicode_wb_data.c"

/* Additional encodings */
#include "euc_jp.c"
#include "euc_jp_prop.c"
#include "euc_kr.c"
#include "euc_tw.c"
#include "sjis.c"
#include "sjis_prop.c"
#include "iso8859_1.c"
#include "iso8859_2.c"
#include "iso8859_3.c"
#include "iso8859_4.c"
#include "iso8859_5.c"
#include "iso8859_6.c"
#include "iso8859_7.c"
#include "iso8859_8.c"
#include "iso8859_9.c"
#include "iso8859_10.c"
#include "iso8859_11.c"
#include "iso8859_13.c"
#include "iso8859_14.c"
#include "iso8859_15.c"
#include "iso8859_16.c"
#include "big5.c"
#include "cp1251.c"
#include "gb18030.c"
#include "koi8.c"
#include "koi8_r.c"
