//! Generated by nexus v0.9.1 — do not edit

const std = @import("std");
const maxArgs: usize = 32;
const slash = @import("slash.zig");

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"integer",
    @"string_sq",
    @"string_dq",
    @"variable",
    @"var_braced",
    @"dollar_paren",
    @"at_paren",
    @"proc_sub_in",
    @"proc_sub_out",
    @"lparen",
    @"rparen",
    @"lbrace",
    @"rbrace",
    @"lbracket",
    @"rbracket",
    @"semi",
    @"and_and",
    @"or_or",
    @"amp",
    @"pipe",
    @"lt",
    @"gt",
    @"gt_gt",
    @"amp_gt",
    @"amp_gt_gt",
    @"fd_lt",
    @"fd_gt",
    @"fd_dup_out",
    @"fd_dup_in",
    @"heredoc_open",
    @"heredoc_open_lit",
    @"heredoc_body",
    @"assign",
    @"name_eq",
    @"indent",
    @"outdent",
    @"comment",
    @"err",
    @"eof",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    aux: u16 = 0,
    // State variables
    paren: i8,
    brace: i8,
    bracket: i8,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
            .paren = 0,
            .brace = 0,
            .bracket = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
        self.paren = 0;
        self.brace = 0;
        self.bracket = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;

    const charFlags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('0'..'9' + 1) |c| table[c] = DIGIT;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['!'] = LETTER;
        table['%'] = LETTER;
        table['*'] = LETTER;
        table['+'] = LETTER;
        table[','] = LETTER;
        table['-'] = LETTER;
        table['.'] = LETTER;
        table['/'] = LETTER;
        table[':'] = LETTER;
        table['?'] = LETTER;
        table['@'] = LETTER;
        table['^'] = LETTER;
        table['_'] = LETTER;
        table['~'] = LETTER;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (charFlags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (charFlags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (charFlags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return isLetter(c) or isDigit(c);
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const wsStart = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const wsCount: u8 = @intCast(@min(self.pos - wsStart, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = wsCount, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        // Newline handling (generated from grammar rules)
        if (c == '\n' or c == '\r') {
            if (c == '\r' and self.pos + 1 < self.source.len and self.source[self.pos + 1] == '\n') {
                self.pos += 2;
                return Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 2 };
            }
                self.pos += 1;
                return Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 1 };
        }
        if (c == '\'') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '\'') {
                    self.pos += 1;
                    if (self.pos < self.source.len and self.source[self.pos] == '\'') { self.pos += 1; continue; }
                    return Token{ .cat = .@"string_sq", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        if (c == '"') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '"') {
                    self.pos += 1;
                    return Token{ .cat = .@"string_dq", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\\') { self.pos += 2; continue; }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Number
        if (isDigit(c)) {
            const tok = self.scanNumber(start, wsCount);
            if (tok.cat == .@"integer") {
                if (self.pos + 3 <= self.source.len and self.source[self.pos + 0] == '>' and self.source[self.pos + 1] == '&' and ((self.source[self.pos + 2] >= '0' and self.source[self.pos + 2] <= '9'))) {
                    self.pos += 3;
                    while (self.pos < self.source.len and ((self.source[self.pos] >= '0' and self.source[self.pos] <= '9'))) self.pos += 1;
                    return Token{ .cat = .@"fd_dup_out", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 3 <= self.source.len and self.source[self.pos + 0] == '<' and self.source[self.pos + 1] == '&' and ((self.source[self.pos + 2] >= '0' and self.source[self.pos + 2] <= '9'))) {
                    self.pos += 3;
                    while (self.pos < self.source.len and ((self.source[self.pos] >= '0' and self.source[self.pos] <= '9'))) self.pos += 1;
                    return Token{ .cat = .@"fd_dup_in", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 1 <= self.source.len and self.source[self.pos + 0] == '>') {
                    self.pos += 1;
                    return Token{ .cat = .@"fd_gt", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 1 <= self.source.len and self.source[self.pos + 0] == '<') {
                    self.pos += 1;
                    return Token{ .cat = .@"fd_lt", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
            }
            return tok;
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, wsCount);
        }
        if (c == '$') {
            const nc = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if (nc == '{') {
                self.pos += 2;
                while (self.pos < self.source.len and self.source[self.pos] != '}' and self.source[self.pos] != '\n') self.pos += 1;
                if (self.pos < self.source.len and self.source[self.pos] == '}') self.pos += 1;
                return Token{ .cat = .@"var_braced", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
            }
            if ((nc >= 'a' and nc <= 'z') or (nc >= 'A' and nc <= 'Z') or nc == '_') {
                self.pos += 1;
                while (self.pos < self.source.len) {
                    const vc = self.source[self.pos];
                    if (!((vc >= 'a' and vc <= 'z') or (vc >= 'A' and vc <= 'Z') or (vc >= '0' and vc <= '9') or vc == '_')) break;
                    self.pos += 1;
                }
                return Token{ .cat = .@"variable", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
            }
            if (nc >= '0' and nc <= '9') {
                self.pos += 2;
                return Token{ .cat = .@"variable", .pre = wsCount, .pos = start, .len = 2 };
            }
        }
        // Comment (scan to end of line)
        if (c == '#') {
            while (self.pos < self.source.len and self.source[self.pos] != '\n') {
                self.pos += 1;
            }
            return Token{ .cat = .@"comment", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '$' => blk: {
                if (self.peek() == '(') {
                    self.pos += 1;
                self.paren += 1;
                    break :blk Token{ .cat = .@"dollar_paren", .pre = wsCount, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '&' => blk: {
                if (self.peek() == '&') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"and_and", .pre = wsCount, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    if (self.peek() == '>') {
                        self.pos += 1;
                    break :blk Token{ .cat = .@"amp_gt_gt", .pre = wsCount, .pos = start, .len = 3 };
                    }
                    break :blk Token{ .cat = .@"amp_gt", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"amp", .pre = wsCount, .pos = start, .len = 1 };
            },
            '(' => blk: {
                self.paren += 1;
                    break :blk Token{ .cat = .@"lparen", .pre = wsCount, .pos = start, .len = 1 };
            },
            ')' => blk: {
                self.paren -= 1;
                    break :blk Token{ .cat = .@"rparen", .pre = wsCount, .pos = start, .len = 1 };
            },
            ';' => Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 1 },
            '<' => blk: {
                if (self.peek() == '(') {
                    self.pos += 1;
                self.paren += 1;
                    break :blk Token{ .cat = .@"proc_sub_in", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"lt", .pre = wsCount, .pos = start, .len = 1 };
            },
            '=' => Token{ .cat = .@"assign", .pre = wsCount, .pos = start, .len = 1 },
            '>' => blk: {
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"gt_gt", .pre = wsCount, .pos = start, .len = 2 };
                }
                if (self.peek() == '(') {
                    self.pos += 1;
                self.paren += 1;
                    break :blk Token{ .cat = .@"proc_sub_out", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"gt", .pre = wsCount, .pos = start, .len = 1 };
            },
            '@' => blk: {
                if (self.peek() == '(') {
                    self.pos += 1;
                self.paren += 1;
                    break :blk Token{ .cat = .@"at_paren", .pre = wsCount, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '[' => blk: {
                self.bracket += 1;
                    break :blk Token{ .cat = .@"lbracket", .pre = wsCount, .pos = start, .len = 1 };
            },
            ']' => blk: {
                self.bracket -= 1;
                    break :blk Token{ .cat = .@"rbracket", .pre = wsCount, .pos = start, .len = 1 };
            },
            '{' => blk: {
                self.brace += 1;
                    break :blk Token{ .cat = .@"lbrace", .pre = wsCount, .pos = start, .len = 1 };
            },
            '|' => blk: {
                if (self.peek() == '|') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"or_or", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"pipe", .pre = wsCount, .pos = start, .len = 1 };
            },
            '}' => blk: {
                self.brace -= 1;
                    break :blk Token{ .cat = .@"rbrace", .pre = wsCount, .pos = start, .len = 1 };
            },
            else => Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        // Decimal integer
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        return Token{ .cat = .@"integer", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

pub const Lexer = if (@hasDecl(slash, "Lexer")) slash.Lexer else BaseLexer;

// =============================================================================
// Tag Enum (re-exported from language module)
// =============================================================================
pub const Tag = slash.Tag;

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// Parser
// =============================================================================

pub const Parser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injectedToken: ?u16 = null,
    lastMatchedId: u16 = 0,

    stateStack: std.ArrayListUnmanaged(u16) = .empty,
    valueStack: std.ArrayListUnmanaged(Sexp) = .empty,

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) Parser {
        var p = Parser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *Parser) void {
        self.arena.deinit();
    }

    fn allocator(self: *Parser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *Parser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *Parser, startSym: u16) !Sexp {
        const startState = getStartState(startSym);
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        try self.stateStack.append(self.allocator(), startState);

        while (true) {
            const state = self.stateStack.getLast();
            const sym = if (self.injectedToken) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shiftTarget| {
                    action = shiftTarget;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.valueStack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injectedToken != null) {
                    try self.valueStack.append(self.allocator(), .nil);
                    self.injectedToken = null;
                } else {
                    try self.valueStack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = if (self.lastMatchedId != 0) self.lastMatchedId else self.lexer.base.aux,
                    } });
                    self.lastMatchedId = 0;
                    self.lexer.base.aux = 0;
                    self.current = self.lexer.next();
                }
                try self.stateStack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const ruleId: u16 = @intCast(-action - 2);
                var pass: [maxArgs]Sexp = undefined;
                const len = ruleLen[ruleId];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.valueStack.pop().?;
                    _ = self.stateStack.pop();
                }

                const result = self.executeAction(ruleId, pass[0..len]);

                if (isAcceptRule(ruleId)) return result;

                try self.valueStack.append(self.allocator(), result);

                const gotoState = self.stateStack.getLast();
                const next = getAction(gotoState, ruleLhs[ruleId]);
                if (next <= 0) return error.ParseError;
                try self.stateStack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *Parser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *Parser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *Parser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *Parser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *Parser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *Parser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skipPos = (pos == .nil and len == 0);
        const total = if (skipPos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skipPos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *Parser, ruleId: u16, pass: []Sexp) Sexp {
        return switch (ruleId) {
            0 => pass[1],
            1 => self.spreadList(pass[0], pass[1]),
            2 => .{ .list = &[_]Sexp{} },
            3 => self.sexpPosSpread(.@"sequence", pass[0], pass[1]),
            4 => self.list(pass),
            5 => self.list(pass),
            6 => self.list(pass),
            7 => self.list(pass),
            8 => self.list(pass),
            9 => self.list(pass),
            10 => self.list(pass),
            11 => self.list(pass),
            12 => self.sexp(.@"seq_always", &.{pass[1]}),
            13 => self.sexp(.@"seq_always", &.{.nil}),
            14 => self.sexp(.@"seq_and", &.{pass[1]}),
            15 => self.sexp(.@"seq_or", &.{pass[1]}),
            16 => self.sexp(.@"seq_bg", &.{pass[1]}),
            17 => self.sexp(.@"seq_bg", &.{.nil}),
            18 => pass[0],
            19 => self.spreadList(pass[0], pass[1]),
            20 => .{ .list = &[_]Sexp{} },
            21 => self.spreadList(pass[0], pass[1]),
            22 => self.sexpPosSpread(.@"pipeline", pass[0], pass[1]),
            23 => pass[1],
            24 => self.list(pass),
            25 => self.list(pass),
            26 => self.sexp(.@"subshell", &.{pass[1]}),
            27 => self.sexp(.@"subshell", &.{pass[1], pass[3]}),
            28 => self.sexp(.@"block", &.{pass[1]}),
            29 => self.sexp(.@"block", &.{pass[1], pass[3]}),
            30 => self.spreadList(pass[0], pass[1]),
            31 => .{ .list = &[_]Sexp{} },
            32 => self.spreadList(pass[0], pass[1]),
            33 => self.sexpSpread(.@"redirects", pass[0]),
            34 => self.spreadList(pass[0], pass[1]),
            35 => .{ .list = &[_]Sexp{} },
            36 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"command" }) catch break :blk .nil; out.append(self.allocator(), .nil) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; if (pass[1] == .list) for (pass[1].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            37 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"command" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; if (pass[2] == .list) for (pass[2].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            38 => self.spreadList(pass[0], pass[1]),
            39 => .{ .list = &[_]Sexp{} },
            40 => self.spreadList(pass[0], pass[1]),
            41 => self.sexpSpread(.@"env_binds", pass[0]),
            42 => self.sexpSpread(.@"assigns", pass[0]),
            43 => self.sexp(.@"env_bind", &.{pass[0], pass[1]}),
            44 => self.sexp(.@"scalar", &.{pass[0]}),
            45 => self.sexpSpread(.@"list", pass[1]),
            46 => self.spreadList(pass[0], pass[1]),
            47 => .{ .list = &[_]Sexp{} },
            48 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            49 => self.list(pass),
            50 => self.list(pass),
            51 => self.sexp(.@"word", &.{pass[0]}),
            52 => self.sexp(.@"word", &.{pass[0]}),
            53 => self.sexp(.@"word", &.{pass[0]}),
            54 => self.sexp(.@"word", &.{pass[0]}),
            55 => self.sexp(.@"var", &.{pass[0]}),
            56 => self.sexp(.@"var_braced", &.{pass[0]}),
            57 => self.sexp(.@"cmd_subst", &.{pass[1]}),
            58 => self.sexp(.@"list_capture", &.{pass[1]}),
            59 => self.sexp(.@"proc_sub_in", &.{pass[1]}),
            60 => self.sexp(.@"proc_sub_out", &.{pass[1]}),
            61 => self.list(pass),
            62 => self.sexp(.@"word", &.{pass[0]}),
            63 => self.sexp(.@"word", &.{pass[0]}),
            64 => self.sexp(.@"if", &.{pass[1], pass[2], .nil}),
            65 => self.sexp(.@"if", &.{pass[1], pass[2], pass[3]}),
            66 => pass[0],
            67 => self.sexp(.@"cond_and", &.{pass[0], pass[2]}),
            68 => self.sexp(.@"cond_or", &.{pass[0], pass[2]}),
            69 => self.sexp(.@"else", &.{pass[1]}),
            70 => self.sexp(.@"elif", &.{pass[1]}),
            71 => self.sexp(.@"body", &.{pass[1]}),
            72 => self.sexp(.@"body", &.{pass[1]}),
            73 => self.sexp(.@"while", &.{pass[1], pass[2]}),
            74 => self.sexp(.@"for", &.{pass[1], pass[3], pass[4]}),
            75 => self.sexp(.@"match", &.{pass[1], pass[2]}),
            76 => self.sexpSpread(.@"match_arms", pass[1]),
            77 => self.sexpSpread(.@"match_arms", pass[1]),
            78 => self.spreadList(pass[0], pass[1]),
            79 => .{ .list = &[_]Sexp{} },
            80 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), pass[0]) catch break :blk .nil; if (pass[1] == .list) for (pass[1].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            81 => pass[1],
            82 => .nil,
            83 => self.sexp(.@"match_arm", &.{pass[0], pass[1]}),
            84 => self.sexp(.@"cmd_def", &.{pass[1], pass[2]}),
            85 => self.spreadList(pass[0], pass[1]),
            86 => self.sexpSpread(.@"words", pass[0]),
            87 => self.sexp(.@"redir_read", &.{pass[1]}),
            88 => self.sexp(.@"redir_read_fd", &.{pass[0], pass[1]}),
            89 => self.sexp(.@"redir_write", &.{pass[1]}),
            90 => self.sexp(.@"redir_write_fd", &.{pass[0], pass[1]}),
            91 => self.sexp(.@"redir_append", &.{pass[1]}),
            92 => self.sexp(.@"redir_both", &.{pass[1]}),
            93 => self.sexp(.@"redir_both_append", &.{pass[1]}),
            94 => self.sexp(.@"redir_dup_out", &.{pass[0]}),
            95 => self.sexp(.@"redir_dup_in", &.{pass[0]}),
            96 => self.sexp(.@"redir_heredoc", &.{pass[0], pass[1]}),
            97 => self.sexp(.@"redir_heredoc_lit", &.{pass[0], pass[1]}),
            98 => self.list(pass),
            else => .nil,
        };
    }

    fn tokenToSymbol(self: *Parser, token: Token) u16 {
        return switch (token.cat) {
            .@"eof" => 1,
            .@"ident" => self.identToSymbol(token),
            .@"semi" => 37,
            .@"and_and" => 38,
            .@"or_or" => 39,
            .@"amp" => 40,
            .@"pipe" => 43,
            .@"lparen" => 44,
            .@"rparen" => 45,
            .@"lbrace" => 46,
            .@"rbrace" => 47,
            .@"name_eq" => 53,
            .@"lbracket" => 54,
            .@"rbracket" => 55,
            .@"integer" => 58,
            .@"string_sq" => 59,
            .@"string_dq" => 60,
            .@"variable" => 61,
            .@"var_braced" => 62,
            .@"dollar_paren" => 63,
            .@"at_paren" => 64,
            .@"proc_sub_in" => 65,
            .@"proc_sub_out" => 66,
            .@"assign" => 67,
            .@"indent" => 70,
            .@"outdent" => 71,
            .@"lt" => 79,
            .@"fd_lt" => 80,
            .@"gt" => 81,
            .@"fd_gt" => 82,
            .@"gt_gt" => 83,
            .@"amp_gt" => 84,
            .@"amp_gt_gt" => 85,
            .@"fd_dup_out" => 86,
            .@"fd_dup_in" => 87,
            .@"heredoc_open" => 88,
            .@"heredoc_body" => 89,
            .@"heredoc_open_lit" => 90,
            else => 2, // error
        };
    }

    fn identToSymbol(self: *Parser, token: Token) u16 {
        const text = self.source[token.pos..][0..token.len];
        if (text.len == 0) return symIdent;
        if (self.tryIdentAsKeyword(token, text)) |sym| return sym;
        return symIdent;
    }

    fn tryIdentAsKeyword(self: *Parser, token: Token, text: []const u8) ?u16 {
        _ = token;
        const state = self.stateStack.getLast();
        if (slash.keywordAs(text)) |id| {
            const idIdx = @intFromEnum(id);
            const sym = keywordToSymbol[idIdx];
            if (sym != 0 and getAction(state, sym) != 0) {
                self.lastMatchedId = @intCast(idIdx);
                return sym;
            }
            const fallback = keywordFallbackSymbol;
            if (fallback != 0 and getAction(state, fallback) != 0) {
                self.lastMatchedId = @intCast(idIdx);
                return fallback;
            }
        }
        return null;
    }

    pub fn parseProgram(self: *Parser) !Sexp {
        self.injectedToken = SYM_program_START;
        return self.doParse(SYM_program);
    }
};

// Symbol IDs
const SYM_program: u16 = 3;
const SYM_program_START: u16 = 91;
const symIdent: u16 = 57;

// Mapping from slash.KeywordId to grammar symbol IDs (computed at comptime)
const keywordToSymbol = blk: {
    var arr: [512]u16 = .{0} ** 512;
    if (@hasField(slash.KeywordId, "SEMI")) arr[@intFromEnum(slash.KeywordId.SEMI)] = 37;
    if (@hasField(slash.KeywordId, "AND_AND")) arr[@intFromEnum(slash.KeywordId.AND_AND)] = 38;
    if (@hasField(slash.KeywordId, "OR_OR")) arr[@intFromEnum(slash.KeywordId.OR_OR)] = 39;
    if (@hasField(slash.KeywordId, "AMP")) arr[@intFromEnum(slash.KeywordId.AMP)] = 40;
    if (@hasField(slash.KeywordId, "PIPE")) arr[@intFromEnum(slash.KeywordId.PIPE)] = 43;
    if (@hasField(slash.KeywordId, "LPAREN")) arr[@intFromEnum(slash.KeywordId.LPAREN)] = 44;
    if (@hasField(slash.KeywordId, "RPAREN")) arr[@intFromEnum(slash.KeywordId.RPAREN)] = 45;
    if (@hasField(slash.KeywordId, "LBRACE")) arr[@intFromEnum(slash.KeywordId.LBRACE)] = 46;
    if (@hasField(slash.KeywordId, "RBRACE")) arr[@intFromEnum(slash.KeywordId.RBRACE)] = 47;
    if (@hasField(slash.KeywordId, "NAME_EQ")) arr[@intFromEnum(slash.KeywordId.NAME_EQ)] = 53;
    if (@hasField(slash.KeywordId, "LBRACKET")) arr[@intFromEnum(slash.KeywordId.LBRACKET)] = 54;
    if (@hasField(slash.KeywordId, "RBRACKET")) arr[@intFromEnum(slash.KeywordId.RBRACKET)] = 55;
    if (@hasField(slash.KeywordId, "IDENT")) arr[@intFromEnum(slash.KeywordId.IDENT)] = 57;
    if (@hasField(slash.KeywordId, "INTEGER")) arr[@intFromEnum(slash.KeywordId.INTEGER)] = 58;
    if (@hasField(slash.KeywordId, "STRING_SQ")) arr[@intFromEnum(slash.KeywordId.STRING_SQ)] = 59;
    if (@hasField(slash.KeywordId, "STRING_DQ")) arr[@intFromEnum(slash.KeywordId.STRING_DQ)] = 60;
    if (@hasField(slash.KeywordId, "VARIABLE")) arr[@intFromEnum(slash.KeywordId.VARIABLE)] = 61;
    if (@hasField(slash.KeywordId, "VAR_BRACED")) arr[@intFromEnum(slash.KeywordId.VAR_BRACED)] = 62;
    if (@hasField(slash.KeywordId, "DOLLAR_PAREN")) arr[@intFromEnum(slash.KeywordId.DOLLAR_PAREN)] = 63;
    if (@hasField(slash.KeywordId, "AT_PAREN")) arr[@intFromEnum(slash.KeywordId.AT_PAREN)] = 64;
    if (@hasField(slash.KeywordId, "PROC_SUB_IN")) arr[@intFromEnum(slash.KeywordId.PROC_SUB_IN)] = 65;
    if (@hasField(slash.KeywordId, "PROC_SUB_OUT")) arr[@intFromEnum(slash.KeywordId.PROC_SUB_OUT)] = 66;
    if (@hasField(slash.KeywordId, "ASSIGN")) arr[@intFromEnum(slash.KeywordId.ASSIGN)] = 67;
    if (@hasField(slash.KeywordId, "IF")) arr[@intFromEnum(slash.KeywordId.IF)] = 68;
    if (@hasField(slash.KeywordId, "ELSE")) arr[@intFromEnum(slash.KeywordId.ELSE)] = 69;
    if (@hasField(slash.KeywordId, "INDENT")) arr[@intFromEnum(slash.KeywordId.INDENT)] = 70;
    if (@hasField(slash.KeywordId, "OUTDENT")) arr[@intFromEnum(slash.KeywordId.OUTDENT)] = 71;
    if (@hasField(slash.KeywordId, "WHILE")) arr[@intFromEnum(slash.KeywordId.WHILE)] = 72;
    if (@hasField(slash.KeywordId, "FOR")) arr[@intFromEnum(slash.KeywordId.FOR)] = 73;
    if (@hasField(slash.KeywordId, "IN")) arr[@intFromEnum(slash.KeywordId.IN)] = 74;
    if (@hasField(slash.KeywordId, "MATCH")) arr[@intFromEnum(slash.KeywordId.MATCH)] = 75;
    if (@hasField(slash.KeywordId, "CMD")) arr[@intFromEnum(slash.KeywordId.CMD)] = 77;
    if (@hasField(slash.KeywordId, "LT")) arr[@intFromEnum(slash.KeywordId.LT)] = 79;
    if (@hasField(slash.KeywordId, "FD_LT")) arr[@intFromEnum(slash.KeywordId.FD_LT)] = 80;
    if (@hasField(slash.KeywordId, "GT")) arr[@intFromEnum(slash.KeywordId.GT)] = 81;
    if (@hasField(slash.KeywordId, "FD_GT")) arr[@intFromEnum(slash.KeywordId.FD_GT)] = 82;
    if (@hasField(slash.KeywordId, "GT_GT")) arr[@intFromEnum(slash.KeywordId.GT_GT)] = 83;
    if (@hasField(slash.KeywordId, "AMP_GT")) arr[@intFromEnum(slash.KeywordId.AMP_GT)] = 84;
    if (@hasField(slash.KeywordId, "AMP_GT_GT")) arr[@intFromEnum(slash.KeywordId.AMP_GT_GT)] = 85;
    if (@hasField(slash.KeywordId, "FD_DUP_OUT")) arr[@intFromEnum(slash.KeywordId.FD_DUP_OUT)] = 86;
    if (@hasField(slash.KeywordId, "FD_DUP_IN")) arr[@intFromEnum(slash.KeywordId.FD_DUP_IN)] = 87;
    if (@hasField(slash.KeywordId, "HEREDOC_OPEN")) arr[@intFromEnum(slash.KeywordId.HEREDOC_OPEN)] = 88;
    if (@hasField(slash.KeywordId, "HEREDOC_BODY")) arr[@intFromEnum(slash.KeywordId.HEREDOC_BODY)] = 89;
    if (@hasField(slash.KeywordId, "HEREDOC_OPEN_LIT")) arr[@intFromEnum(slash.KeywordId.HEREDOC_OPEN_LIT)] = 90;
    break :blk arr;
};
const keywordFallbackSymbol: u16 = 0;

const ruleLhs = [_]u16{ 3, 36, 36, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 41, 41, 42, 7, 8, 9, 9, 10, 10, 11, 11, 48, 48, 49, 12, 50, 50, 13, 13, 51, 51, 52, 14, 15, 16, 17, 17, 56, 56, 18, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 22, 22, 23, 23, 23, 24, 24, 25, 25, 26, 27, 28, 29, 29, 76, 76, 30, 31, 31, 32, 33, 78, 34, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 92 };
const ruleLen = [_]u8{ 2, 2, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 0, 2, 2, 2, 1, 1, 3, 4, 3, 4, 2, 0, 2, 1, 2, 0, 2, 3, 2, 0, 2, 1, 1, 2, 1, 3, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 1, 1, 1, 3, 4, 1, 3, 3, 2, 2, 3, 3, 3, 5, 3, 3, 3, 2, 0, 2, 2, 1, 2, 3, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2 };

// Parse Table: 162 states × 93 symbols
const numStates = 162;
const numSymbols = 93;

const sparse = [numStates][]const i16{
    &.{3,1,91,2},
    &.{1,-1},
    &.{4,37,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{1,-1},
    &.{7,40,9,5,10,7,13,6,14,19,16,8,20,16,23,41,44,38,52,39,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32},
    &.{1,-20,8,42,37,-20,38,-20,39,-20,40,-20,42,43,43,44,45,-20,46,-20,47,-20,70,-20,71,-20},
    &.{1,-26,37,-26,38,-26,39,-26,40,-26,43,-26,45,-26,46,-26,47,-26,70,-26,71,-26},
    &.{1,-27,37,-27,38,-27,39,-27,40,-27,43,-27,45,-27,46,-27,47,-27,70,-27,71,-27},
    &.{1,-41,16,46,37,-41,38,-41,39,-41,40,-41,45,-41,47,-41,51,45,53,30,57,-41,58,-41,59,-41,60,-41,61,-41,62,-41,63,-41,64,-41,65,-41,66,-41,71,-41},
    &.{1,-53,37,-53,38,-53,39,-53,40,-53,43,-53,45,-53,46,-53,47,-53,53,-53,55,-53,57,-53,58,-53,59,-53,60,-53,61,-53,62,-53,63,-53,64,-53,65,-53,66,-53,67,-53,70,-53,71,-53,79,-53,80,-53,81,-53,82,-53,83,-53,84,-53,85,-53,86,-53,87,-53,88,-53,90,-53},
    &.{1,-54,37,-54,38,-54,39,-54,40,-54,43,-54,45,-54,46,-54,47,-54,53,-54,55,-54,57,-54,58,-54,59,-54,60,-54,61,-54,62,-54,63,-54,64,-54,65,-54,66,-54,67,-54,70,-54,71,-54,79,-54,80,-54,81,-54,82,-54,83,-54,84,-54,85,-54,86,-54,87,-54,88,-54,90,-54},
    &.{4,47,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{4,48,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{4,49,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{1,-56,37,-56,38,-56,39,-56,40,-56,43,-56,45,-56,46,-56,47,-56,53,-56,55,-56,57,-56,58,-56,59,-56,60,-56,61,-56,62,-56,63,-56,64,-56,65,-56,66,-56,67,-56,70,-56,71,-56,79,-56,80,-56,81,-56,82,-56,83,-56,84,-56,85,-56,86,-56,87,-56,88,-56,90,-56},
    &.{1,-6,37,-6,38,-6,39,-6,40,-6,45,-6,47,-6,71,-6},
    &.{1,-37,19,65,20,56,21,53,35,52,37,-37,38,-37,39,-37,40,-37,43,-37,45,-37,46,-37,47,-37,50,64,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,70,-37,71,-37,79,67,80,61,81,62,82,66,83,50,84,58,85,63,86,57,87,59,88,54,90,55},
    &.{1,-12,37,-12,38,-12,39,-12,40,-12,45,-12,47,-12,71,-12},
    &.{7,40,9,5,10,7,13,6,14,19,16,8,20,16,23,68,44,38,52,39,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32},
    &.{20,69,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32},
    &.{1,-7,37,-7,38,-7,39,-7,40,-7,45,-7,47,-7,71,-7},
    &.{57,70},
    &.{1,-10,37,-10,38,-10,39,-10,40,-10,45,-10,47,-10,71,-10},
    &.{20,56,21,71,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{1,-55,37,-55,38,-55,39,-55,40,-55,43,-55,45,-55,46,-55,47,-55,53,-55,55,-55,57,-55,58,-55,59,-55,60,-55,61,-55,62,-55,63,-55,64,-55,65,-55,66,-55,67,-55,70,-55,71,-55,79,-55,80,-55,81,-55,82,-55,83,-55,84,-55,85,-55,86,-55,87,-55,88,-55,90,-55},
    &.{1,-11,37,-11,38,-11,39,-11,40,-11,45,-11,47,-11,71,-11},
    &.{1,-9,37,-9,38,-9,39,-9,40,-9,45,-9,47,-9,71,-9},
    &.{1,-4,6,74,36,76,37,77,38,75,39,73,40,72,45,-4,47,-4,71,-4},
    &.{1,-8,37,-8,38,-8,39,-8,40,-8,45,-8,47,-8,71,-8},
    &.{57,78},
    &.{17,79,20,56,21,80,53,60,54,81,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{1,-57,37,-57,38,-57,39,-57,40,-57,43,-57,45,-57,46,-57,47,-57,53,-57,55,-57,57,-57,58,-57,59,-57,60,-57,61,-57,62,-57,63,-57,64,-57,65,-57,66,-57,67,-57,70,-57,71,-57,79,-57,80,-57,81,-57,82,-57,83,-57,84,-57,85,-57,86,-57,87,-57,88,-57,90,-57},
    &.{4,82,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{1,-58,37,-58,38,-58,39,-58,40,-58,43,-58,45,-58,46,-58,47,-58,53,-58,55,-58,57,-58,58,-58,59,-58,60,-58,61,-58,62,-58,63,-58,64,-58,65,-58,66,-58,67,-58,70,-58,71,-58,79,-58,80,-58,81,-58,82,-58,83,-58,84,-58,85,-58,86,-58,87,-58,88,-58,90,-58},
    &.{4,83,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{1,-13,37,-13,38,-13,39,-13,40,-13,45,-13,47,-13,71,-13},
    &.{1,-44,37,-44,38,-44,39,-44,40,-44,45,-44,47,-44,57,-43,58,-43,59,-43,60,-43,61,-43,62,-43,63,-43,64,-43,65,-43,66,-43,71,-44},
    &.{1,-2},
    &.{4,84,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{57,-43,58,-43,59,-43,60,-43,61,-43,62,-43,63,-43,64,-43,65,-43,66,-43},
    &.{38,-68,39,-68,46,-68,70,-68},
    &.{25,86,38,87,39,85,46,88,70,89},
    &.{1,-22,8,90,37,-22,38,-22,39,-22,40,-22,41,91,43,44,45,-22,46,-22,47,-22,70,-22,71,-22},
    &.{1,-24,37,-24,38,-24,39,-24,40,-24,45,-24,46,-24,47,-24,70,-24,71,-24},
    &.{9,92,10,7,13,6,14,19,16,8,20,16,44,38,52,39,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32},
    &.{1,-42,37,-42,38,-42,39,-42,40,-42,45,-42,47,-42,57,-42,58,-42,59,-42,60,-42,61,-42,62,-42,63,-42,64,-42,65,-42,66,-42,71,-42},
    &.{1,-41,16,46,37,-41,38,-41,39,-41,40,-41,45,-41,47,-41,51,93,53,30,57,-41,58,-41,59,-41,60,-41,61,-41,62,-41,63,-41,64,-41,65,-41,66,-41,71,-41},
    &.{45,94},
    &.{45,95},
    &.{45,96},
    &.{20,56,21,97,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{1,-65,37,-65,38,-65,39,-65,40,-65,43,-65,45,-65,46,-65,47,-65,53,-65,55,-65,57,-65,58,-65,59,-65,60,-65,61,-65,62,-65,63,-65,64,-65,65,-65,66,-65,67,-65,70,-65,71,-65,79,-65,80,-65,81,-65,82,-65,83,-65,84,-65,85,-65,86,-65,87,-65,88,-65,90,-65},
    &.{1,-52,37,-52,38,-52,39,-52,40,-52,43,-52,45,-52,46,-52,47,-52,53,-52,57,-52,58,-52,59,-52,60,-52,61,-52,62,-52,63,-52,64,-52,65,-52,66,-52,67,-52,70,-52,71,-52,79,-52,80,-52,81,-52,82,-52,83,-52,84,-52,85,-52,86,-52,87,-52,88,-52,90,-52},
    &.{1,-51,37,-51,38,-51,39,-51,40,-51,43,-51,45,-51,46,-51,47,-51,53,-51,57,-51,58,-51,59,-51,60,-51,61,-51,62,-51,63,-51,64,-51,65,-51,66,-51,67,-51,70,-51,71,-51,79,-51,80,-51,81,-51,82,-51,83,-51,84,-51,85,-51,86,-51,87,-51,88,-51,90,-51},
    &.{89,98},
    &.{89,99},
    &.{1,-63,37,-63,38,-63,39,-63,40,-63,43,-63,45,-63,46,-63,47,-63,53,-63,55,-63,57,-63,58,-63,59,-63,60,-63,61,-63,62,-63,63,-63,64,-63,65,-63,66,-63,67,-63,70,-63,71,-63,79,-63,80,-63,81,-63,82,-63,83,-63,84,-63,85,-63,86,-63,87,-63,88,-63,90,-63},
    &.{1,-96,37,-96,38,-96,39,-96,40,-96,43,-96,45,-96,46,-96,47,-96,53,-96,57,-96,58,-96,59,-96,60,-96,61,-96,62,-96,63,-96,64,-96,65,-96,66,-96,67,-96,70,-96,71,-96,79,-96,80,-96,81,-96,82,-96,83,-96,84,-96,85,-96,86,-96,87,-96,88,-96,90,-96},
    &.{20,56,21,100,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{1,-97,37,-97,38,-97,39,-97,40,-97,43,-97,45,-97,46,-97,47,-97,53,-97,57,-97,58,-97,59,-97,60,-97,61,-97,62,-97,63,-97,64,-97,65,-97,66,-97,67,-97,70,-97,71,-97,79,-97,80,-97,81,-97,82,-97,83,-97,84,-97,85,-97,86,-97,87,-97,88,-97,90,-97},
    &.{1,-64,37,-64,38,-64,39,-64,40,-64,43,-64,45,-64,46,-64,47,-64,53,-64,55,-64,57,-64,58,-64,59,-64,60,-64,61,-64,62,-64,63,-64,64,-64,65,-64,66,-64,67,-64,70,-64,71,-64,79,-64,80,-64,81,-64,82,-64,83,-64,84,-64,85,-64,86,-64,87,-64,88,-64,90,-64},
    &.{20,56,21,101,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{20,56,21,102,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{20,56,21,103,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{1,-38,37,-38,38,-38,39,-38,40,-38,43,-38,45,-38,46,-38,47,-38,70,-38,71,-38},
    &.{1,-37,19,65,20,56,21,53,35,52,37,-37,38,-37,39,-37,40,-37,43,-37,45,-37,46,-37,47,-37,50,104,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,70,-37,71,-37,79,67,80,61,81,62,82,66,83,50,84,58,85,63,86,57,87,59,88,54,90,55},
    &.{20,56,21,105,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{20,56,21,106,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{25,107,38,87,39,85,46,88,70,89},
    &.{1,-37,19,65,20,56,21,53,35,52,37,-37,38,-37,39,-37,40,-37,43,-37,45,-37,46,-37,47,-37,50,108,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,70,-37,71,-37,79,67,80,61,81,62,82,66,83,50,84,58,85,63,86,57,87,59,88,54,90,55},
    &.{74,109},
    &.{29,110,46,111,70,112},
    &.{1,-19,5,113,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,37,-19,38,-19,39,-19,40,-19,44,38,45,-19,46,34,47,-19,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,71,-19,72,4,73,21,75,23,77,29},
    &.{5,114,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{1,-4,6,74,36,115,37,77,38,75,39,73,40,72,45,-4,47,-4,71,-4},
    &.{5,116,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{1,-5,45,-5,47,-5,71,-5},
    &.{1,-15,5,117,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,37,-15,38,-15,39,-15,40,-15,44,38,45,-15,46,34,47,-15,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,71,-15,72,4,73,21,75,23,77,29},
    &.{25,118,46,88,70,89},
    &.{1,-45,37,-45,38,-45,39,-45,40,-45,45,-45,47,-45,53,-45,57,-45,58,-45,59,-45,60,-45,61,-45,62,-45,63,-45,64,-45,65,-45,66,-45,71,-45},
    &.{1,-46,37,-46,38,-46,39,-46,40,-46,45,-46,47,-46,53,-46,57,-46,58,-46,59,-46,60,-46,61,-46,62,-46,63,-46,64,-46,65,-46,66,-46,71,-46},
    &.{18,120,20,56,21,119,53,60,55,-49,56,121,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51},
    &.{45,122},
    &.{47,123},
    &.{45,124},
    &.{7,125,9,5,10,7,13,6,14,19,16,8,20,16,44,38,52,39,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32},
    &.{1,-75,37,-75,38,-75,39,-75,40,-75,45,-75,47,-75,71,-75},
    &.{7,126,9,5,10,7,13,6,14,19,16,8,20,16,44,38,52,39,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32},
    &.{4,127,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{4,128,5,27,7,15,9,5,10,7,11,25,13,6,14,19,15,17,16,8,20,16,22,20,26,28,27,26,28,22,33,35,44,38,46,34,52,36,53,30,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,68,18,72,4,73,21,75,23,77,29},
    &.{1,-22,8,90,37,-22,38,-22,39,-22,40,-22,41,129,43,44,45,-22,46,-22,47,-22,70,-22,71,-22},
    &.{1,-23,37,-23,38,-23,39,-23,40,-23,45,-23,46,-23,47,-23,70,-23,71,-23},
    &.{1,-25,37,-25,38,-25,39,-25,40,-25,43,-25,45,-25,46,-25,47,-25,70,-25,71,-25},
    &.{1,-40,37,-40,38,-40,39,-40,40,-40,45,-40,47,-40,57,-40,58,-40,59,-40,60,-40,61,-40,62,-40,63,-40,64,-40,65,-40,66,-40,71,-40},
    &.{1,-59,37,-59,38,-59,39,-59,40,-59,43,-59,45,-59,46,-59,47,-59,53,-59,55,-59,57,-59,58,-59,59,-59,60,-59,61,-59,62,-59,63,-59,64,-59,65,-59,66,-59,67,-59,70,-59,71,-59,79,-59,80,-59,81,-59,82,-59,83,-59,84,-59,85,-59,86,-59,87,-59,88,-59,90,-59},
    &.{1,-60,37,-60,38,-60,39,-60,40,-60,43,-60,45,-60,46,-60,47,-60,53,-60,55,-60,57,-60,58,-60,59,-60,60,-60,61,-60,62,-60,63,-60,64,-60,65,-60,66,-60,67,-60,70,-60,71,-60,79,-60,80,-60,81,-60,82,-60,83,-60,84,-60,85,-60,86,-60,87,-60,88,-60,90,-60},
    &.{1,-61,37,-61,38,-61,39,-61,40,-61,43,-61,45,-61,46,-61,47,-61,53,-61,55,-61,57,-61,58,-61,59,-61,60,-61,61,-61,62,-61,63,-61,64,-61,65,-61,66,-61,67,-61,70,-61,71,-61,79,-61,80,-61,81,-61,82,-61,83,-61,84,-61,85,-61,86,-61,87,-61,88,-61,90,-61},
    &.{1,-93,37,-93,38,-93,39,-93,40,-93,43,-93,45,-93,46,-93,47,-93,53,-93,57,-93,58,-93,59,-93,60,-93,61,-93,62,-93,63,-93,64,-93,65,-93,66,-93,67,-93,70,-93,71,-93,79,-93,80,-93,81,-93,82,-93,83,-93,84,-93,85,-93,86,-93,87,-93,88,-93,90,-93},
    &.{1,-98,37,-98,38,-98,39,-98,40,-98,43,-98,45,-98,46,-98,47,-98,53,-98,57,-98,58,-98,59,-98,60,-98,61,-98,62,-98,63,-98,64,-98,65,-98,66,-98,67,-98,70,-98,71,-98,79,-98,80,-98,81,-98,82,-98,83,-98,84,-98,85,-98,86,-98,87,-98,88,-98,90,-98},
    &.{1,-99,37,-99,38,-99,39,-99,40,-99,43,-99,45,-99,46,-99,47,-99,53,-99,57,-99,58,-99,59,-99,60,-99,61,-99,62,-99,63,-99,64,-99,65,-99,66,-99,67,-99,70,-99,71,-99,79,-99,80,-99,81,-99,82,-99,83,-99,84,-99,85,-99,86,-99,87,-99,88,-99,90,-99},
    &.{1,-94,37,-94,38,-94,39,-94,40,-94,43,-94,45,-94,46,-94,47,-94,53,-94,57,-94,58,-94,59,-94,60,-94,61,-94,62,-94,63,-94,64,-94,65,-94,66,-94,67,-94,70,-94,71,-94,79,-94,80,-94,81,-94,82,-94,83,-94,84,-94,85,-94,86,-94,87,-94,88,-94,90,-94},
    &.{1,-90,37,-90,38,-90,39,-90,40,-90,43,-90,45,-90,46,-90,47,-90,53,-90,57,-90,58,-90,59,-90,60,-90,61,-90,62,-90,63,-90,64,-90,65,-90,66,-90,67,-90,70,-90,71,-90,79,-90,80,-90,81,-90,82,-90,83,-90,84,-90,85,-90,86,-90,87,-90,88,-90,90,-90},
    &.{1,-91,37,-91,38,-91,39,-91,40,-91,43,-91,45,-91,46,-91,47,-91,53,-91,57,-91,58,-91,59,-91,60,-91,61,-91,62,-91,63,-91,64,-91,65,-91,66,-91,67,-91,70,-91,71,-91,79,-91,80,-91,81,-91,82,-91,83,-91,84,-91,85,-91,86,-91,87,-91,88,-91,90,-91},
    &.{1,-95,37,-95,38,-95,39,-95,40,-95,43,-95,45,-95,46,-95,47,-95,53,-95,57,-95,58,-95,59,-95,60,-95,61,-95,62,-95,63,-95,64,-95,65,-95,66,-95,67,-95,70,-95,71,-95,79,-95,80,-95,81,-95,82,-95,83,-95,84,-95,85,-95,86,-95,87,-95,88,-95,90,-95},
    &.{1,-36,37,-36,38,-36,39,-36,40,-36,43,-36,45,-36,46,-36,47,-36,70,-36,71,-36},
    &.{1,-92,37,-92,38,-92,39,-92,40,-92,43,-92,45,-92,46,-92,47,-92,53,-92,57,-92,58,-92,59,-92,60,-92,61,-92,62,-92,63,-92,64,-92,65,-92,66,-92,67,-92,70,-92,71,-92,79,-92,80,-92,81,-92,82,-92,83,-92,84,-92,85,-92,86,-92,87,-92,88,-92,90,-92},
    &.{1,-89,37,-89,38,-89,39,-89,40,-89,43,-89,45,-89,46,-89,47,-89,53,-89,57,-89,58,-89,59,-89,60,-89,61,-89,62,-89,63,-89,64,-89,65,-89,66,-89,67,-89,70,-89,71,-89,79,-89,80,-89,81,-89,82,-89,83,-89,84,-89,85,-89,86,-89,87,-89,88,-89,90,-89},
    &.{1,-66,24,130,37,-66,38,-66,39,-66,40,-66,45,-66,47,-66,69,131,71,-66},
    &.{1,-39,37,-39,38,-39,39,-39,40,-39,43,-39,45,-39,46,-39,47,-39,70,-39,71,-39},
    &.{20,56,21,133,34,132,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,78,134},
    &.{1,-77,37,-77,38,-77,39,-77,40,-77,45,-77,47,-77,71,-77},
    &.{20,56,21,133,30,136,32,137,34,135,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,78,134},
    &.{20,56,21,133,30,138,32,137,34,135,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,78,134},
    &.{1,-18,37,-18,38,-18,39,-18,40,-18,45,-18,47,-18,71,-18},
    &.{1,-17,37,-17,38,-17,39,-17,40,-17,45,-17,47,-17,71,-17},
    &.{1,-3,45,-3,47,-3,71,-3},
    &.{1,-16,37,-16,38,-16,39,-16,40,-16,45,-16,47,-16,71,-16},
    &.{1,-14,37,-14,38,-14,39,-14,40,-14,45,-14,47,-14,71,-14},
    &.{1,-86,37,-86,38,-86,39,-86,40,-86,45,-86,47,-86,71,-86},
    &.{20,56,21,119,46,-49,53,60,55,-49,56,139,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,70,-49},
    &.{55,140},
    &.{55,-50},
    &.{1,-62,37,-62,38,-62,39,-62,40,-62,43,-62,45,-62,46,-62,47,-62,53,-62,55,-62,57,-62,58,-62,59,-62,60,-62,61,-62,62,-62,63,-62,64,-62,65,-62,66,-62,67,-62,70,-62,71,-62,79,-62,80,-62,81,-62,82,-62,83,-62,84,-62,85,-62,86,-62,87,-62,88,-62,90,-62},
    &.{1,-30,12,143,35,141,37,-30,38,-30,39,-30,40,-30,45,-30,47,-30,49,142,71,-30,79,67,80,61,81,62,82,66,83,50,84,58,85,63,86,57,87,59,88,54,90,55},
    &.{1,-28,12,144,35,141,37,-28,38,-28,39,-28,40,-28,43,-28,45,-28,46,-28,47,-28,49,142,70,-28,71,-28,79,67,80,61,81,62,82,66,83,50,84,58,85,63,86,57,87,59,88,54,90,55},
    &.{38,-70,39,-70,46,-70,70,-70},
    &.{38,-69,39,-69,46,-69,70,-69},
    &.{47,145},
    &.{71,146},
    &.{1,-21,37,-21,38,-21,39,-21,40,-21,45,-21,46,-21,47,-21,70,-21,71,-21},
    &.{1,-67,37,-67,38,-67,39,-67,40,-67,45,-67,47,-67,71,-67},
    &.{22,148,25,147,46,88,68,18,70,89},
    &.{25,149,46,88,70,89},
    &.{20,56,21,119,46,-49,53,60,56,150,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,70,-49},
    &.{46,-88,70,-88},
    &.{25,151,46,88,70,89},
    &.{47,152},
    &.{31,153,37,155,47,-81,71,-81,76,154},
    &.{71,156},
    &.{46,-48,55,-48,70,-48},
    &.{1,-47,37,-47,38,-47,39,-47,40,-47,45,-47,47,-47,53,-47,57,-47,58,-47,59,-47,60,-47,61,-47,62,-47,63,-47,64,-47,65,-47,66,-47,71,-47},
    &.{1,-33,35,157,37,-33,38,-33,39,-33,40,-33,43,-33,45,-33,46,-33,47,-33,48,158,70,-33,71,-33,79,67,80,61,81,62,82,66,83,50,84,58,85,63,86,57,87,59,88,54,90,55},
    &.{1,-35,37,-35,38,-35,39,-35,40,-35,43,-35,45,-35,46,-35,47,-35,70,-35,71,-35},
    &.{1,-31,37,-31,38,-31,39,-31,40,-31,45,-31,47,-31,71,-31},
    &.{1,-29,37,-29,38,-29,39,-29,40,-29,43,-29,45,-29,46,-29,47,-29,70,-29,71,-29},
    &.{1,-73,37,-73,38,-73,39,-73,40,-73,45,-73,47,-73,69,-73,71,-73},
    &.{1,-74,37,-74,38,-74,39,-74,40,-74,45,-74,47,-74,69,-74,71,-74},
    &.{1,-71,37,-71,38,-71,39,-71,40,-71,45,-71,47,-71,71,-71},
    &.{1,-72,37,-72,38,-72,39,-72,40,-72,45,-72,47,-72,71,-72},
    &.{1,-76,37,-76,38,-76,39,-76,40,-76,45,-76,47,-76,71,-76},
    &.{46,-87,70,-87},
    &.{37,-85,47,-85,71,-85},
    &.{1,-78,37,-78,38,-78,39,-78,40,-78,45,-78,47,-78,71,-78},
    &.{31,153,37,155,47,-81,71,-81,76,159},
    &.{47,-82,71,-82},
    &.{20,56,21,133,32,160,34,135,37,-84,47,-84,53,60,57,9,58,10,59,24,60,14,61,31,62,33,63,11,64,12,65,13,66,32,67,51,71,-84,78,134},
    &.{1,-79,37,-79,38,-79,39,-79,40,-79,45,-79,47,-79,71,-79},
    &.{1,-33,35,157,37,-33,38,-33,39,-33,40,-33,43,-33,45,-33,46,-33,47,-33,48,161,70,-33,71,-33,79,67,80,61,81,62,82,66,83,50,84,58,85,63,86,57,87,59,88,54,90,55},
    &.{1,-34,37,-34,38,-34,39,-34,40,-34,43,-34,45,-34,46,-34,47,-34,70,-34,71,-34},
    &.{47,-80,71,-80},
    &.{37,-83,47,-83,71,-83},
    &.{1,-32,37,-32,38,-32,39,-32,40,-32,43,-32,45,-32,46,-32,47,-32,70,-32,71,-32},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const xExcludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (xExcludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const startStates = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
};

fn getStartState(startSym: u16) u16 {
    for (startStates) |entry| {
        if (entry.sym == startSym) return entry.state;
    }
    return 0;
}

const acceptRules = [_]u16{ 98 };

fn isAcceptRule(ruleId: u16) bool {
    for (acceptRules) |ar| if (ruleId == ar) return true;
    return false;
}
