//! Generated by nexus v0.9.1 — do not edit

const std = @import("std");
const maxArgs: usize = 32;
const slash = @import("slash.zig");

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"integer",
    @"string_sq",
    @"string_dq",
    @"variable",
    @"var_braced",
    @"dollar_paren",
    @"at_paren",
    @"lparen",
    @"rparen",
    @"lbrace",
    @"rbrace",
    @"lbracket",
    @"rbracket",
    @"semi",
    @"and_and",
    @"or_or",
    @"amp",
    @"pipe",
    @"lt",
    @"gt",
    @"gt_gt",
    @"amp_gt",
    @"amp_gt_gt",
    @"fd_lt",
    @"fd_gt",
    @"fd_dup_out",
    @"fd_dup_in",
    @"assign",
    @"name_eq",
    @"indent",
    @"outdent",
    @"comment",
    @"err",
    @"eof",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    aux: u16 = 0,
    // State variables
    paren: i8,
    brace: i8,
    bracket: i8,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
            .paren = 0,
            .brace = 0,
            .bracket = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
        self.paren = 0;
        self.brace = 0;
        self.bracket = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;

    const charFlags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('0'..'9' + 1) |c| table[c] = DIGIT;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['!'] = LETTER;
        table['%'] = LETTER;
        table['*'] = LETTER;
        table['+'] = LETTER;
        table[','] = LETTER;
        table['-'] = LETTER;
        table['.'] = LETTER;
        table['/'] = LETTER;
        table[':'] = LETTER;
        table['?'] = LETTER;
        table['@'] = LETTER;
        table['^'] = LETTER;
        table['_'] = LETTER;
        table['~'] = LETTER;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (charFlags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (charFlags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (charFlags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return isLetter(c) or isDigit(c);
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const wsStart = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const wsCount: u8 = @intCast(@min(self.pos - wsStart, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = wsCount, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        // Newline handling (generated from grammar rules)
        if (c == '\n' or c == '\r') {
            if (c == '\r' and self.pos + 1 < self.source.len and self.source[self.pos + 1] == '\n') {
                self.pos += 2;
                return Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 2 };
            }
                self.pos += 1;
                return Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 1 };
        }
        if (c == '\'') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '\'') {
                    self.pos += 1;
                    if (self.pos < self.source.len and self.source[self.pos] == '\'') { self.pos += 1; continue; }
                    return Token{ .cat = .@"string_sq", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        if (c == '"') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '"') {
                    self.pos += 1;
                    return Token{ .cat = .@"string_dq", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\\') { self.pos += 2; continue; }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Number
        if (isDigit(c)) {
            const tok = self.scanNumber(start, wsCount);
            if (tok.cat == .@"integer") {
                if (self.pos + 3 <= self.source.len and self.source[self.pos + 0] == '>' and self.source[self.pos + 1] == '&' and ((self.source[self.pos + 2] >= '0' and self.source[self.pos + 2] <= '9'))) {
                    self.pos += 3;
                    while (self.pos < self.source.len and ((self.source[self.pos] >= '0' and self.source[self.pos] <= '9'))) self.pos += 1;
                    return Token{ .cat = .@"fd_dup_out", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 3 <= self.source.len and self.source[self.pos + 0] == '<' and self.source[self.pos + 1] == '&' and ((self.source[self.pos + 2] >= '0' and self.source[self.pos + 2] <= '9'))) {
                    self.pos += 3;
                    while (self.pos < self.source.len and ((self.source[self.pos] >= '0' and self.source[self.pos] <= '9'))) self.pos += 1;
                    return Token{ .cat = .@"fd_dup_in", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 1 <= self.source.len and self.source[self.pos + 0] == '>') {
                    self.pos += 1;
                    return Token{ .cat = .@"fd_gt", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 1 <= self.source.len and self.source[self.pos + 0] == '<') {
                    self.pos += 1;
                    return Token{ .cat = .@"fd_lt", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
            }
            return tok;
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, wsCount);
        }
        if (c == '$') {
            const nc = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if (nc == '{') {
                self.pos += 2;
                while (self.pos < self.source.len and self.source[self.pos] != '}' and self.source[self.pos] != '\n') self.pos += 1;
                if (self.pos < self.source.len and self.source[self.pos] == '}') self.pos += 1;
                return Token{ .cat = .@"var_braced", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
            }
            if ((nc >= 'a' and nc <= 'z') or (nc >= 'A' and nc <= 'Z') or nc == '_') {
                self.pos += 1;
                while (self.pos < self.source.len) {
                    const vc = self.source[self.pos];
                    if (!((vc >= 'a' and vc <= 'z') or (vc >= 'A' and vc <= 'Z') or (vc >= '0' and vc <= '9') or vc == '_')) break;
                    self.pos += 1;
                }
                return Token{ .cat = .@"variable", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
            }
            if (nc >= '0' and nc <= '9') {
                self.pos += 2;
                return Token{ .cat = .@"variable", .pre = wsCount, .pos = start, .len = 2 };
            }
        }
        // Comment (scan to end of line)
        if (c == '#') {
            while (self.pos < self.source.len and self.source[self.pos] != '\n') {
                self.pos += 1;
            }
            return Token{ .cat = .@"comment", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '$' => blk: {
                if (self.peek() == '(') {
                    self.pos += 1;
                self.paren += 1;
                    break :blk Token{ .cat = .@"dollar_paren", .pre = wsCount, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '&' => blk: {
                if (self.peek() == '&') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"and_and", .pre = wsCount, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    if (self.peek() == '>') {
                        self.pos += 1;
                    break :blk Token{ .cat = .@"amp_gt_gt", .pre = wsCount, .pos = start, .len = 3 };
                    }
                    break :blk Token{ .cat = .@"amp_gt", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"amp", .pre = wsCount, .pos = start, .len = 1 };
            },
            '(' => blk: {
                self.paren += 1;
                    break :blk Token{ .cat = .@"lparen", .pre = wsCount, .pos = start, .len = 1 };
            },
            ')' => blk: {
                self.paren -= 1;
                    break :blk Token{ .cat = .@"rparen", .pre = wsCount, .pos = start, .len = 1 };
            },
            ';' => Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 1 },
            '<' => Token{ .cat = .@"lt", .pre = wsCount, .pos = start, .len = 1 },
            '=' => Token{ .cat = .@"assign", .pre = wsCount, .pos = start, .len = 1 },
            '>' => blk: {
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"gt_gt", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"gt", .pre = wsCount, .pos = start, .len = 1 };
            },
            '@' => blk: {
                if (self.peek() == '(') {
                    self.pos += 1;
                self.paren += 1;
                    break :blk Token{ .cat = .@"at_paren", .pre = wsCount, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '[' => blk: {
                self.bracket += 1;
                    break :blk Token{ .cat = .@"lbracket", .pre = wsCount, .pos = start, .len = 1 };
            },
            ']' => blk: {
                self.bracket -= 1;
                    break :blk Token{ .cat = .@"rbracket", .pre = wsCount, .pos = start, .len = 1 };
            },
            '{' => blk: {
                self.brace += 1;
                    break :blk Token{ .cat = .@"lbrace", .pre = wsCount, .pos = start, .len = 1 };
            },
            '|' => blk: {
                if (self.peek() == '|') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"or_or", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"pipe", .pre = wsCount, .pos = start, .len = 1 };
            },
            '}' => blk: {
                self.brace -= 1;
                    break :blk Token{ .cat = .@"rbrace", .pre = wsCount, .pos = start, .len = 1 };
            },
            else => Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        // Decimal integer
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        return Token{ .cat = .@"integer", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

pub const Lexer = if (@hasDecl(slash, "Lexer")) slash.Lexer else BaseLexer;

// =============================================================================
// Tag Enum (re-exported from language module)
// =============================================================================
pub const Tag = slash.Tag;

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// Parser
// =============================================================================

pub const Parser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injectedToken: ?u16 = null,
    lastMatchedId: u16 = 0,

    stateStack: std.ArrayListUnmanaged(u16) = .empty,
    valueStack: std.ArrayListUnmanaged(Sexp) = .empty,

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) Parser {
        var p = Parser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *Parser) void {
        self.arena.deinit();
    }

    fn allocator(self: *Parser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *Parser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *Parser, startSym: u16) !Sexp {
        const startState = getStartState(startSym);
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        try self.stateStack.append(self.allocator(), startState);

        while (true) {
            const state = self.stateStack.getLast();
            const sym = if (self.injectedToken) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shiftTarget| {
                    action = shiftTarget;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.valueStack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injectedToken != null) {
                    try self.valueStack.append(self.allocator(), .nil);
                    self.injectedToken = null;
                } else {
                    try self.valueStack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = if (self.lastMatchedId != 0) self.lastMatchedId else self.lexer.base.aux,
                    } });
                    self.lastMatchedId = 0;
                    self.lexer.base.aux = 0;
                    self.current = self.lexer.next();
                }
                try self.stateStack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const ruleId: u16 = @intCast(-action - 2);
                var pass: [maxArgs]Sexp = undefined;
                const len = ruleLen[ruleId];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.valueStack.pop().?;
                    _ = self.stateStack.pop();
                }

                const result = self.executeAction(ruleId, pass[0..len]);

                if (isAcceptRule(ruleId)) return result;

                try self.valueStack.append(self.allocator(), result);

                const gotoState = self.stateStack.getLast();
                const next = getAction(gotoState, ruleLhs[ruleId]);
                if (next <= 0) return error.ParseError;
                try self.stateStack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *Parser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *Parser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *Parser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *Parser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *Parser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *Parser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skipPos = (pos == .nil and len == 0);
        const total = if (skipPos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skipPos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *Parser, ruleId: u16, pass: []Sexp) Sexp {
        return switch (ruleId) {
            0 => pass[1],
            1 => self.spreadList(pass[0], pass[1]),
            2 => .{ .list = &[_]Sexp{} },
            3 => self.sexpPosSpread(.@"sequence", pass[0], pass[1]),
            4 => self.list(pass),
            5 => self.list(pass),
            6 => self.list(pass),
            7 => self.list(pass),
            8 => self.list(pass),
            9 => self.list(pass),
            10 => self.list(pass),
            11 => self.sexp(.@"seq_always", &.{pass[1]}),
            12 => self.sexp(.@"seq_always", &.{.nil}),
            13 => self.sexp(.@"seq_and", &.{pass[1]}),
            14 => self.sexp(.@"seq_or", &.{pass[1]}),
            15 => self.sexp(.@"seq_bg", &.{pass[1]}),
            16 => self.sexp(.@"seq_bg", &.{.nil}),
            17 => pass[0],
            18 => self.spreadList(pass[0], pass[1]),
            19 => .{ .list = &[_]Sexp{} },
            20 => self.spreadList(pass[0], pass[1]),
            21 => self.sexpPosSpread(.@"pipeline", pass[0], pass[1]),
            22 => pass[1],
            23 => self.list(pass),
            24 => self.list(pass),
            25 => self.sexp(.@"subshell", &.{pass[1]}),
            26 => self.sexp(.@"subshell", &.{pass[1], pass[3]}),
            27 => self.sexp(.@"block", &.{pass[1]}),
            28 => self.sexp(.@"block", &.{pass[1], pass[3]}),
            29 => self.spreadList(pass[0], pass[1]),
            30 => .{ .list = &[_]Sexp{} },
            31 => self.spreadList(pass[0], pass[1]),
            32 => self.sexpSpread(.@"redirects", pass[0]),
            33 => self.spreadList(pass[0], pass[1]),
            34 => .{ .list = &[_]Sexp{} },
            35 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"command" }) catch break :blk .nil; out.append(self.allocator(), .nil) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; if (pass[1] == .list) for (pass[1].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            36 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"command" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; if (pass[2] == .list) for (pass[2].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            37 => self.spreadList(pass[0], pass[1]),
            38 => .{ .list = &[_]Sexp{} },
            39 => self.spreadList(pass[0], pass[1]),
            40 => self.sexpSpread(.@"env_binds", pass[0]),
            41 => self.sexpSpread(.@"assigns", pass[0]),
            42 => self.sexp(.@"env_bind", &.{pass[0], pass[1]}),
            43 => self.sexp(.@"scalar", &.{pass[0]}),
            44 => self.sexpSpread(.@"list", pass[1]),
            45 => self.spreadList(pass[0], pass[1]),
            46 => .{ .list = &[_]Sexp{} },
            47 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            48 => self.list(pass),
            49 => self.list(pass),
            50 => self.sexp(.@"word", &.{pass[0]}),
            51 => self.sexp(.@"word", &.{pass[0]}),
            52 => self.sexp(.@"word", &.{pass[0]}),
            53 => self.sexp(.@"word", &.{pass[0]}),
            54 => self.sexp(.@"var", &.{pass[0]}),
            55 => self.sexp(.@"var_braced", &.{pass[0]}),
            56 => self.sexp(.@"cmd_subst", &.{pass[1]}),
            57 => self.sexp(.@"list_capture", &.{pass[1]}),
            58 => self.list(pass),
            59 => self.sexp(.@"word", &.{pass[0]}),
            60 => self.sexp(.@"word", &.{pass[0]}),
            61 => self.sexp(.@"if", &.{pass[1], pass[2], .nil}),
            62 => self.sexp(.@"if", &.{pass[1], pass[2], pass[3]}),
            63 => pass[0],
            64 => self.sexp(.@"cond_and", &.{pass[0], pass[2]}),
            65 => self.sexp(.@"cond_or", &.{pass[0], pass[2]}),
            66 => self.sexp(.@"else", &.{pass[1]}),
            67 => self.sexp(.@"elif", &.{pass[1]}),
            68 => self.sexp(.@"body", &.{pass[1]}),
            69 => self.sexp(.@"body", &.{pass[1]}),
            70 => self.sexp(.@"while", &.{pass[1], pass[2]}),
            71 => self.sexp(.@"for", &.{pass[1], pass[3], pass[4]}),
            72 => self.sexp(.@"cmd_def", &.{pass[1], pass[2]}),
            73 => self.spreadList(pass[0], pass[1]),
            74 => self.sexpSpread(.@"words", pass[0]),
            75 => self.sexp(.@"redir_read", &.{pass[1]}),
            76 => self.sexp(.@"redir_read_fd", &.{pass[0], pass[1]}),
            77 => self.sexp(.@"redir_write", &.{pass[1]}),
            78 => self.sexp(.@"redir_write_fd", &.{pass[0], pass[1]}),
            79 => self.sexp(.@"redir_append", &.{pass[1]}),
            80 => self.sexp(.@"redir_both", &.{pass[1]}),
            81 => self.sexp(.@"redir_both_append", &.{pass[1]}),
            82 => self.sexp(.@"redir_dup_out", &.{pass[0]}),
            83 => self.sexp(.@"redir_dup_in", &.{pass[0]}),
            84 => self.list(pass),
            else => .nil,
        };
    }

    fn tokenToSymbol(self: *Parser, token: Token) u16 {
        return switch (token.cat) {
            .@"eof" => 1,
            .@"ident" => self.identToSymbol(token),
            .@"semi" => 32,
            .@"and_and" => 33,
            .@"or_or" => 34,
            .@"amp" => 35,
            .@"pipe" => 38,
            .@"lparen" => 39,
            .@"rparen" => 40,
            .@"lbrace" => 41,
            .@"rbrace" => 42,
            .@"name_eq" => 48,
            .@"lbracket" => 49,
            .@"rbracket" => 50,
            .@"integer" => 53,
            .@"string_sq" => 54,
            .@"string_dq" => 55,
            .@"variable" => 56,
            .@"var_braced" => 57,
            .@"dollar_paren" => 58,
            .@"at_paren" => 59,
            .@"assign" => 60,
            .@"indent" => 63,
            .@"outdent" => 64,
            .@"lt" => 70,
            .@"fd_lt" => 71,
            .@"gt" => 72,
            .@"fd_gt" => 73,
            .@"gt_gt" => 74,
            .@"amp_gt" => 75,
            .@"amp_gt_gt" => 76,
            .@"fd_dup_out" => 77,
            .@"fd_dup_in" => 78,
            else => 2, // error
        };
    }

    fn identToSymbol(self: *Parser, token: Token) u16 {
        const text = self.source[token.pos..][0..token.len];
        if (text.len == 0) return symIdent;
        if (self.tryIdentAsKeyword(token, text)) |sym| return sym;
        return symIdent;
    }

    fn tryIdentAsKeyword(self: *Parser, token: Token, text: []const u8) ?u16 {
        _ = token;
        const state = self.stateStack.getLast();
        if (slash.keywordAs(text)) |id| {
            const idIdx = @intFromEnum(id);
            const sym = keywordToSymbol[idIdx];
            if (sym != 0 and getAction(state, sym) != 0) {
                self.lastMatchedId = @intCast(idIdx);
                return sym;
            }
            const fallback = keywordFallbackSymbol;
            if (fallback != 0 and getAction(state, fallback) != 0) {
                self.lastMatchedId = @intCast(idIdx);
                return fallback;
            }
        }
        return null;
    }

    pub fn parseProgram(self: *Parser) !Sexp {
        self.injectedToken = SYM_program_START;
        return self.doParse(SYM_program);
    }
};

// Symbol IDs
const SYM_program: u16 = 3;
const SYM_program_START: u16 = 79;
const symIdent: u16 = 52;

// Mapping from slash.KeywordId to grammar symbol IDs (computed at comptime)
const keywordToSymbol = blk: {
    var arr: [512]u16 = .{0} ** 512;
    if (@hasField(slash.KeywordId, "SEMI")) arr[@intFromEnum(slash.KeywordId.SEMI)] = 32;
    if (@hasField(slash.KeywordId, "AND_AND")) arr[@intFromEnum(slash.KeywordId.AND_AND)] = 33;
    if (@hasField(slash.KeywordId, "OR_OR")) arr[@intFromEnum(slash.KeywordId.OR_OR)] = 34;
    if (@hasField(slash.KeywordId, "AMP")) arr[@intFromEnum(slash.KeywordId.AMP)] = 35;
    if (@hasField(slash.KeywordId, "PIPE")) arr[@intFromEnum(slash.KeywordId.PIPE)] = 38;
    if (@hasField(slash.KeywordId, "LPAREN")) arr[@intFromEnum(slash.KeywordId.LPAREN)] = 39;
    if (@hasField(slash.KeywordId, "RPAREN")) arr[@intFromEnum(slash.KeywordId.RPAREN)] = 40;
    if (@hasField(slash.KeywordId, "LBRACE")) arr[@intFromEnum(slash.KeywordId.LBRACE)] = 41;
    if (@hasField(slash.KeywordId, "RBRACE")) arr[@intFromEnum(slash.KeywordId.RBRACE)] = 42;
    if (@hasField(slash.KeywordId, "NAME_EQ")) arr[@intFromEnum(slash.KeywordId.NAME_EQ)] = 48;
    if (@hasField(slash.KeywordId, "LBRACKET")) arr[@intFromEnum(slash.KeywordId.LBRACKET)] = 49;
    if (@hasField(slash.KeywordId, "RBRACKET")) arr[@intFromEnum(slash.KeywordId.RBRACKET)] = 50;
    if (@hasField(slash.KeywordId, "IDENT")) arr[@intFromEnum(slash.KeywordId.IDENT)] = 52;
    if (@hasField(slash.KeywordId, "INTEGER")) arr[@intFromEnum(slash.KeywordId.INTEGER)] = 53;
    if (@hasField(slash.KeywordId, "STRING_SQ")) arr[@intFromEnum(slash.KeywordId.STRING_SQ)] = 54;
    if (@hasField(slash.KeywordId, "STRING_DQ")) arr[@intFromEnum(slash.KeywordId.STRING_DQ)] = 55;
    if (@hasField(slash.KeywordId, "VARIABLE")) arr[@intFromEnum(slash.KeywordId.VARIABLE)] = 56;
    if (@hasField(slash.KeywordId, "VAR_BRACED")) arr[@intFromEnum(slash.KeywordId.VAR_BRACED)] = 57;
    if (@hasField(slash.KeywordId, "DOLLAR_PAREN")) arr[@intFromEnum(slash.KeywordId.DOLLAR_PAREN)] = 58;
    if (@hasField(slash.KeywordId, "AT_PAREN")) arr[@intFromEnum(slash.KeywordId.AT_PAREN)] = 59;
    if (@hasField(slash.KeywordId, "ASSIGN")) arr[@intFromEnum(slash.KeywordId.ASSIGN)] = 60;
    if (@hasField(slash.KeywordId, "IF")) arr[@intFromEnum(slash.KeywordId.IF)] = 61;
    if (@hasField(slash.KeywordId, "ELSE")) arr[@intFromEnum(slash.KeywordId.ELSE)] = 62;
    if (@hasField(slash.KeywordId, "INDENT")) arr[@intFromEnum(slash.KeywordId.INDENT)] = 63;
    if (@hasField(slash.KeywordId, "OUTDENT")) arr[@intFromEnum(slash.KeywordId.OUTDENT)] = 64;
    if (@hasField(slash.KeywordId, "WHILE")) arr[@intFromEnum(slash.KeywordId.WHILE)] = 65;
    if (@hasField(slash.KeywordId, "FOR")) arr[@intFromEnum(slash.KeywordId.FOR)] = 66;
    if (@hasField(slash.KeywordId, "IN")) arr[@intFromEnum(slash.KeywordId.IN)] = 67;
    if (@hasField(slash.KeywordId, "CMD")) arr[@intFromEnum(slash.KeywordId.CMD)] = 68;
    if (@hasField(slash.KeywordId, "LT")) arr[@intFromEnum(slash.KeywordId.LT)] = 70;
    if (@hasField(slash.KeywordId, "FD_LT")) arr[@intFromEnum(slash.KeywordId.FD_LT)] = 71;
    if (@hasField(slash.KeywordId, "GT")) arr[@intFromEnum(slash.KeywordId.GT)] = 72;
    if (@hasField(slash.KeywordId, "FD_GT")) arr[@intFromEnum(slash.KeywordId.FD_GT)] = 73;
    if (@hasField(slash.KeywordId, "GT_GT")) arr[@intFromEnum(slash.KeywordId.GT_GT)] = 74;
    if (@hasField(slash.KeywordId, "AMP_GT")) arr[@intFromEnum(slash.KeywordId.AMP_GT)] = 75;
    if (@hasField(slash.KeywordId, "AMP_GT_GT")) arr[@intFromEnum(slash.KeywordId.AMP_GT_GT)] = 76;
    if (@hasField(slash.KeywordId, "FD_DUP_OUT")) arr[@intFromEnum(slash.KeywordId.FD_DUP_OUT)] = 77;
    if (@hasField(slash.KeywordId, "FD_DUP_IN")) arr[@intFromEnum(slash.KeywordId.FD_DUP_IN)] = 78;
    break :blk arr;
};
const keywordFallbackSymbol: u16 = 0;

const ruleLhs = [_]u16{ 3, 31, 31, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 36, 36, 37, 7, 8, 9, 9, 10, 10, 11, 11, 43, 43, 44, 12, 45, 45, 13, 13, 46, 46, 47, 14, 15, 16, 17, 17, 51, 51, 18, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 22, 22, 23, 23, 23, 24, 24, 25, 25, 26, 27, 28, 69, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 80 };
const ruleLen = [_]u8{ 2, 2, 0, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 0, 2, 2, 2, 1, 1, 3, 4, 3, 4, 2, 0, 2, 1, 2, 0, 2, 3, 2, 0, 2, 1, 1, 2, 1, 3, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 4, 1, 3, 3, 2, 2, 3, 3, 3, 5, 3, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2 };

// Parse Table: 134 states × 81 symbols
const numStates = 134;
const numSymbols = 81;

const sparse = [numStates][]const i16{
    &.{3,1,79,2},
    &.{1,-1},
    &.{4,32,5,25,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{1,-1},
    &.{1,-19,8,35,32,-19,33,-19,34,-19,35,-19,37,37,38,36,40,-19,41,-19,42,-19,63,-19,64,-19},
    &.{1,-25,32,-25,33,-25,34,-25,35,-25,38,-25,40,-25,41,-25,42,-25,63,-25,64,-25},
    &.{1,-26,32,-26,33,-26,34,-26,35,-26,38,-26,40,-26,41,-26,42,-26,63,-26,64,-26},
    &.{4,38,5,25,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{1,-40,16,40,32,-40,33,-40,34,-40,35,-40,40,-40,42,-40,46,39,48,15,52,-40,53,-40,54,-40,55,-40,56,-40,57,-40,58,-40,59,-40,64,-40},
    &.{1,-57,32,-57,33,-57,34,-57,35,-57,38,-57,40,-57,41,-57,42,-57,48,-57,50,-57,52,-57,53,-57,54,-57,55,-57,56,-57,57,-57,58,-57,59,-57,60,-57,63,-57,64,-57,70,-57,71,-57,72,-57,73,-57,74,-57,75,-57,76,-57,77,-57,78,-57},
    &.{7,41,9,4,10,6,13,5,14,20,16,8,20,14,23,43,39,12,47,42,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30},
    &.{4,44,5,25,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{4,45,5,25,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{1,-6,32,-6,33,-6,34,-6,35,-6,40,-6,42,-6,64,-6},
    &.{1,-36,19,51,20,57,21,55,30,47,32,-36,33,-36,34,-36,35,-36,38,-36,40,-36,41,-36,42,-36,45,54,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53,63,-36,64,-36,70,49,71,48,72,46,73,60,74,59,75,61,76,52,77,50,78,56},
    &.{17,62,20,57,21,63,48,58,49,64,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{1,-11,32,-11,33,-11,34,-11,35,-11,40,-11,42,-11,64,-11},
    &.{52,65},
    &.{1,-56,32,-56,33,-56,34,-56,35,-56,38,-56,40,-56,41,-56,42,-56,48,-56,50,-56,52,-56,53,-56,54,-56,55,-56,56,-56,57,-56,58,-56,59,-56,60,-56,63,-56,64,-56,70,-56,71,-56,72,-56,73,-56,74,-56,75,-56,76,-56,77,-56,78,-56},
    &.{1,-7,32,-7,33,-7,34,-7,35,-7,40,-7,42,-7,64,-7},
    &.{20,66,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30},
    &.{1,-12,32,-12,33,-12,34,-12,35,-12,40,-12,42,-12,64,-12},
    &.{7,41,9,4,10,6,13,5,14,20,16,8,20,14,23,67,39,12,47,42,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30},
    &.{1,-10,32,-10,33,-10,34,-10,35,-10,40,-10,42,-10,64,-10},
    &.{1,-9,32,-9,33,-9,34,-9,35,-9,40,-9,42,-9,64,-9},
    &.{1,-4,6,70,31,73,32,72,33,69,34,68,35,71,40,-4,42,-4,64,-4},
    &.{1,-8,32,-8,33,-8,34,-8,35,-8,40,-8,42,-8,64,-8},
    &.{52,74},
    &.{1,-53,32,-53,33,-53,34,-53,35,-53,38,-53,40,-53,41,-53,42,-53,48,-53,50,-53,52,-53,53,-53,54,-53,55,-53,56,-53,57,-53,58,-53,59,-53,60,-53,63,-53,64,-53,70,-53,71,-53,72,-53,73,-53,74,-53,75,-53,76,-53,77,-53,78,-53},
    &.{1,-55,32,-55,33,-55,34,-55,35,-55,38,-55,40,-55,41,-55,42,-55,48,-55,50,-55,52,-55,53,-55,54,-55,55,-55,56,-55,57,-55,58,-55,59,-55,60,-55,63,-55,64,-55,70,-55,71,-55,72,-55,73,-55,74,-55,75,-55,76,-55,77,-55,78,-55},
    &.{4,75,5,25,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{1,-52,32,-52,33,-52,34,-52,35,-52,38,-52,40,-52,41,-52,42,-52,48,-52,50,-52,52,-52,53,-52,54,-52,55,-52,56,-52,57,-52,58,-52,59,-52,60,-52,63,-52,64,-52,70,-52,71,-52,72,-52,73,-52,74,-52,75,-52,76,-52,77,-52,78,-52},
    &.{1,-2},
    &.{1,-43,32,-43,33,-43,34,-43,35,-43,40,-43,42,-43,52,-42,53,-42,54,-42,55,-42,56,-42,57,-42,58,-42,59,-42,64,-43},
    &.{1,-54,32,-54,33,-54,34,-54,35,-54,38,-54,40,-54,41,-54,42,-54,48,-54,50,-54,52,-54,53,-54,54,-54,55,-54,56,-54,57,-54,58,-54,59,-54,60,-54,63,-54,64,-54,70,-54,71,-54,72,-54,73,-54,74,-54,75,-54,76,-54,77,-54,78,-54},
    &.{1,-21,8,76,32,-21,33,-21,34,-21,35,-21,36,77,38,36,40,-21,41,-21,42,-21,63,-21,64,-21},
    &.{9,78,10,6,13,5,14,20,16,8,20,14,39,12,47,42,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30},
    &.{1,-23,32,-23,33,-23,34,-23,35,-23,40,-23,41,-23,42,-23,63,-23,64,-23},
    &.{42,79},
    &.{1,-41,32,-41,33,-41,34,-41,35,-41,40,-41,42,-41,52,-41,53,-41,54,-41,55,-41,56,-41,57,-41,58,-41,59,-41,64,-41},
    &.{1,-40,16,40,32,-40,33,-40,34,-40,35,-40,40,-40,42,-40,46,80,48,15,52,-40,53,-40,54,-40,55,-40,56,-40,57,-40,58,-40,59,-40,64,-40},
    &.{33,-65,34,-65,41,-65,63,-65},
    &.{52,-42,53,-42,54,-42,55,-42,56,-42,57,-42,58,-42,59,-42},
    &.{25,84,33,83,34,82,41,85,63,81},
    &.{40,86},
    &.{40,87},
    &.{20,57,21,88,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{1,-51,32,-51,33,-51,34,-51,35,-51,38,-51,40,-51,41,-51,42,-51,48,-51,52,-51,53,-51,54,-51,55,-51,56,-51,57,-51,58,-51,59,-51,60,-51,63,-51,64,-51,70,-51,71,-51,72,-51,73,-51,74,-51,75,-51,76,-51,77,-51,78,-51},
    &.{20,57,21,89,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{20,57,21,90,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{1,-84,32,-84,33,-84,34,-84,35,-84,38,-84,40,-84,41,-84,42,-84,48,-84,52,-84,53,-84,54,-84,55,-84,56,-84,57,-84,58,-84,59,-84,60,-84,63,-84,64,-84,70,-84,71,-84,72,-84,73,-84,74,-84,75,-84,76,-84,77,-84,78,-84},
    &.{1,-36,19,51,20,57,21,55,30,47,32,-36,33,-36,34,-36,35,-36,38,-36,40,-36,41,-36,42,-36,45,91,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53,63,-36,64,-36,70,49,71,48,72,46,73,60,74,59,75,61,76,52,77,50,78,56},
    &.{20,57,21,92,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{1,-62,32,-62,33,-62,34,-62,35,-62,38,-62,40,-62,41,-62,42,-62,48,-62,50,-62,52,-62,53,-62,54,-62,55,-62,56,-62,57,-62,58,-62,59,-62,60,-62,63,-62,64,-62,70,-62,71,-62,72,-62,73,-62,74,-62,75,-62,76,-62,77,-62,78,-62},
    &.{1,-37,32,-37,33,-37,34,-37,35,-37,38,-37,40,-37,41,-37,42,-37,63,-37,64,-37},
    &.{1,-50,32,-50,33,-50,34,-50,35,-50,38,-50,40,-50,41,-50,42,-50,48,-50,52,-50,53,-50,54,-50,55,-50,56,-50,57,-50,58,-50,59,-50,60,-50,63,-50,64,-50,70,-50,71,-50,72,-50,73,-50,74,-50,75,-50,76,-50,77,-50,78,-50},
    &.{1,-85,32,-85,33,-85,34,-85,35,-85,38,-85,40,-85,41,-85,42,-85,48,-85,52,-85,53,-85,54,-85,55,-85,56,-85,57,-85,58,-85,59,-85,60,-85,63,-85,64,-85,70,-85,71,-85,72,-85,73,-85,74,-85,75,-85,76,-85,77,-85,78,-85},
    &.{1,-60,32,-60,33,-60,34,-60,35,-60,38,-60,40,-60,41,-60,42,-60,48,-60,50,-60,52,-60,53,-60,54,-60,55,-60,56,-60,57,-60,58,-60,59,-60,60,-60,63,-60,64,-60,70,-60,71,-60,72,-60,73,-60,74,-60,75,-60,76,-60,77,-60,78,-60},
    &.{1,-61,32,-61,33,-61,34,-61,35,-61,38,-61,40,-61,41,-61,42,-61,48,-61,50,-61,52,-61,53,-61,54,-61,55,-61,56,-61,57,-61,58,-61,59,-61,60,-61,63,-61,64,-61,70,-61,71,-61,72,-61,73,-61,74,-61,75,-61,76,-61,77,-61,78,-61},
    &.{20,57,21,93,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{20,57,21,94,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{20,57,21,95,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{1,-44,32,-44,33,-44,34,-44,35,-44,40,-44,42,-44,48,-44,52,-44,53,-44,54,-44,55,-44,56,-44,57,-44,58,-44,59,-44,64,-44},
    &.{1,-45,32,-45,33,-45,34,-45,35,-45,40,-45,42,-45,48,-45,52,-45,53,-45,54,-45,55,-45,56,-45,57,-45,58,-45,59,-45,64,-45},
    &.{18,98,20,57,21,96,48,58,50,-48,51,97,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53},
    &.{25,99,41,85,63,81},
    &.{1,-36,19,51,20,57,21,55,30,47,32,-36,33,-36,34,-36,35,-36,38,-36,40,-36,41,-36,42,-36,45,100,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53,63,-36,64,-36,70,49,71,48,72,46,73,60,74,59,75,61,76,52,77,50,78,56},
    &.{25,101,33,83,34,82,41,85,63,81},
    &.{5,102,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{5,103,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{1,-4,6,70,31,104,32,72,33,69,34,68,35,71,40,-4,42,-4,64,-4},
    &.{1,-18,5,105,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,32,-18,33,-18,34,-18,35,-18,39,12,40,-18,41,7,42,-18,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,64,-18,65,10,66,27,68,17},
    &.{1,-14,5,106,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,32,-14,33,-14,34,-14,35,-14,39,12,40,-14,41,7,42,-14,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,64,-14,65,10,66,27,68,17},
    &.{1,-5,40,-5,42,-5,64,-5},
    &.{67,107},
    &.{40,108},
    &.{1,-21,8,76,32,-21,33,-21,34,-21,35,-21,36,109,38,36,40,-21,41,-21,42,-21,63,-21,64,-21},
    &.{1,-22,32,-22,33,-22,34,-22,35,-22,40,-22,41,-22,42,-22,63,-22,64,-22},
    &.{1,-24,32,-24,33,-24,34,-24,35,-24,38,-24,40,-24,41,-24,42,-24,63,-24,64,-24},
    &.{1,-29,12,110,30,111,32,-29,33,-29,34,-29,35,-29,40,-29,42,-29,44,112,64,-29,70,49,71,48,72,46,73,60,74,59,75,61,76,52,77,50,78,56},
    &.{1,-39,32,-39,33,-39,34,-39,35,-39,40,-39,42,-39,52,-39,53,-39,54,-39,55,-39,56,-39,57,-39,58,-39,59,-39,64,-39},
    &.{4,113,5,25,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{7,114,9,4,10,6,13,5,14,20,16,8,20,14,39,12,47,42,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30},
    &.{7,115,9,4,10,6,13,5,14,20,16,8,20,14,39,12,47,42,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30},
    &.{1,-72,32,-72,33,-72,34,-72,35,-72,40,-72,42,-72,64,-72},
    &.{4,116,5,25,7,13,9,4,10,6,11,23,13,5,14,20,15,16,16,8,20,14,22,19,26,26,27,24,28,21,39,12,41,7,47,33,48,15,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,61,22,65,10,66,27,68,17},
    &.{1,-58,32,-58,33,-58,34,-58,35,-58,38,-58,40,-58,41,-58,42,-58,48,-58,50,-58,52,-58,53,-58,54,-58,55,-58,56,-58,57,-58,58,-58,59,-58,60,-58,63,-58,64,-58,70,-58,71,-58,72,-58,73,-58,74,-58,75,-58,76,-58,77,-58,78,-58},
    &.{1,-27,12,117,30,111,32,-27,33,-27,34,-27,35,-27,38,-27,40,-27,41,-27,42,-27,44,112,63,-27,64,-27,70,49,71,48,72,46,73,60,74,59,75,61,76,52,77,50,78,56},
    &.{1,-79,32,-79,33,-79,34,-79,35,-79,38,-79,40,-79,41,-79,42,-79,48,-79,52,-79,53,-79,54,-79,55,-79,56,-79,57,-79,58,-79,59,-79,60,-79,63,-79,64,-79,70,-79,71,-79,72,-79,73,-79,74,-79,75,-79,76,-79,77,-79,78,-79},
    &.{1,-78,32,-78,33,-78,34,-78,35,-78,38,-78,40,-78,41,-78,42,-78,48,-78,52,-78,53,-78,54,-78,55,-78,56,-78,57,-78,58,-78,59,-78,60,-78,63,-78,64,-78,70,-78,71,-78,72,-78,73,-78,74,-78,75,-78,76,-78,77,-78,78,-78},
    &.{1,-77,32,-77,33,-77,34,-77,35,-77,38,-77,40,-77,41,-77,42,-77,48,-77,52,-77,53,-77,54,-77,55,-77,56,-77,57,-77,58,-77,59,-77,60,-77,63,-77,64,-77,70,-77,71,-77,72,-77,73,-77,74,-77,75,-77,76,-77,77,-77,78,-77},
    &.{1,-35,32,-35,33,-35,34,-35,35,-35,38,-35,40,-35,41,-35,42,-35,63,-35,64,-35},
    &.{1,-83,32,-83,33,-83,34,-83,35,-83,38,-83,40,-83,41,-83,42,-83,48,-83,52,-83,53,-83,54,-83,55,-83,56,-83,57,-83,58,-83,59,-83,60,-83,63,-83,64,-83,70,-83,71,-83,72,-83,73,-83,74,-83,75,-83,76,-83,77,-83,78,-83},
    &.{1,-81,32,-81,33,-81,34,-81,35,-81,38,-81,40,-81,41,-81,42,-81,48,-81,52,-81,53,-81,54,-81,55,-81,56,-81,57,-81,58,-81,59,-81,60,-81,63,-81,64,-81,70,-81,71,-81,72,-81,73,-81,74,-81,75,-81,76,-81,77,-81,78,-81},
    &.{1,-80,32,-80,33,-80,34,-80,35,-80,38,-80,40,-80,41,-80,42,-80,48,-80,52,-80,53,-80,54,-80,55,-80,56,-80,57,-80,58,-80,59,-80,60,-80,63,-80,64,-80,70,-80,71,-80,72,-80,73,-80,74,-80,75,-80,76,-80,77,-80,78,-80},
    &.{1,-82,32,-82,33,-82,34,-82,35,-82,38,-82,40,-82,41,-82,42,-82,48,-82,52,-82,53,-82,54,-82,55,-82,56,-82,57,-82,58,-82,59,-82,60,-82,63,-82,64,-82,70,-82,71,-82,72,-82,73,-82,74,-82,75,-82,76,-82,77,-82,78,-82},
    &.{20,57,21,96,41,-48,48,58,50,-48,51,118,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53,63,-48},
    &.{50,-49},
    &.{50,119},
    &.{1,-74,32,-74,33,-74,34,-74,35,-74,40,-74,42,-74,64,-74},
    &.{1,-38,32,-38,33,-38,34,-38,35,-38,38,-38,40,-38,41,-38,42,-38,63,-38,64,-38},
    &.{1,-63,24,120,32,-63,33,-63,34,-63,35,-63,40,-63,42,-63,62,121,64,-63},
    &.{1,-16,32,-16,33,-16,34,-16,35,-16,40,-16,42,-16,64,-16},
    &.{1,-15,32,-15,33,-15,34,-15,35,-15,40,-15,42,-15,64,-15},
    &.{1,-3,40,-3,42,-3,64,-3},
    &.{1,-17,32,-17,33,-17,34,-17,35,-17,40,-17,42,-17,64,-17},
    &.{1,-13,32,-13,33,-13,34,-13,35,-13,40,-13,42,-13,64,-13},
    &.{20,57,21,122,29,123,48,58,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53,69,124},
    &.{1,-59,32,-59,33,-59,34,-59,35,-59,38,-59,40,-59,41,-59,42,-59,48,-59,50,-59,52,-59,53,-59,54,-59,55,-59,56,-59,57,-59,58,-59,59,-59,60,-59,63,-59,64,-59,70,-59,71,-59,72,-59,73,-59,74,-59,75,-59,76,-59,77,-59,78,-59},
    &.{1,-20,32,-20,33,-20,34,-20,35,-20,40,-20,41,-20,42,-20,63,-20,64,-20},
    &.{1,-30,32,-30,33,-30,34,-30,35,-30,40,-30,42,-30,64,-30},
    &.{1,-32,30,125,32,-32,33,-32,34,-32,35,-32,38,-32,40,-32,41,-32,42,-32,43,126,63,-32,64,-32,70,49,71,48,72,46,73,60,74,59,75,61,76,52,77,50,78,56},
    &.{1,-34,32,-34,33,-34,34,-34,35,-34,38,-34,40,-34,41,-34,42,-34,63,-34,64,-34},
    &.{64,127},
    &.{33,-67,34,-67,41,-67,63,-67},
    &.{33,-66,34,-66,41,-66,63,-66},
    &.{42,128},
    &.{1,-28,32,-28,33,-28,34,-28,35,-28,38,-28,40,-28,41,-28,42,-28,63,-28,64,-28},
    &.{41,-47,50,-47,63,-47},
    &.{1,-46,32,-46,33,-46,34,-46,35,-46,40,-46,42,-46,48,-46,52,-46,53,-46,54,-46,55,-46,56,-46,57,-46,58,-46,59,-46,64,-46},
    &.{1,-64,32,-64,33,-64,34,-64,35,-64,40,-64,42,-64,64,-64},
    &.{22,130,25,129,41,85,61,22,63,81},
    &.{20,57,21,96,41,-48,48,58,51,131,52,31,53,28,54,34,55,29,56,18,57,9,58,11,59,30,60,53,63,-48},
    &.{25,132,41,85,63,81},
    &.{41,-76,63,-76},
    &.{1,-32,30,125,32,-32,33,-32,34,-32,35,-32,38,-32,40,-32,41,-32,42,-32,43,133,63,-32,64,-32,70,49,71,48,72,46,73,60,74,59,75,61,76,52,77,50,78,56},
    &.{1,-33,32,-33,33,-33,34,-33,35,-33,38,-33,40,-33,41,-33,42,-33,63,-33,64,-33},
    &.{1,-71,32,-71,33,-71,34,-71,35,-71,40,-71,42,-71,62,-71,64,-71},
    &.{1,-70,32,-70,33,-70,34,-70,35,-70,40,-70,42,-70,62,-70,64,-70},
    &.{1,-68,32,-68,33,-68,34,-68,35,-68,40,-68,42,-68,64,-68},
    &.{1,-69,32,-69,33,-69,34,-69,35,-69,40,-69,42,-69,64,-69},
    &.{41,-75,63,-75},
    &.{1,-73,32,-73,33,-73,34,-73,35,-73,40,-73,42,-73,64,-73},
    &.{1,-31,32,-31,33,-31,34,-31,35,-31,38,-31,40,-31,41,-31,42,-31,63,-31,64,-31},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const xExcludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (xExcludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const startStates = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
};

fn getStartState(startSym: u16) u16 {
    for (startStates) |entry| {
        if (entry.sym == startSym) return entry.state;
    }
    return 0;
}

const acceptRules = [_]u16{ 84 };

fn isAcceptRule(ruleId: u16) bool {
    for (acceptRules) |ar| if (ruleId == ar) return true;
    return false;
}
