//! Generated by nexus v0.9.1 — do not edit

const std = @import("std");
const maxArgs: usize = 32;
const slash = @import("slash.zig");

// SIMD helpers (fallback if simd.zig not available)
const simd = struct {
    fn findByte(haystack: []const u8, needle: u8) usize {
        for (haystack, 0..) |c, i| if (c == needle) return i;
        return haystack.len;
    }
};

// =============================================================================
// TOKEN CATEGORIES
// =============================================================================

pub const TokenCat = enum(u8) {
    @"ident",
    @"integer",
    @"string_sq",
    @"string_dq",
    @"variable",
    @"var_braced",
    @"dollar_paren",
    @"at_paren",
    @"lparen",
    @"rparen",
    @"lbrace",
    @"rbrace",
    @"lbracket",
    @"rbracket",
    @"semi",
    @"and_and",
    @"or_or",
    @"amp",
    @"pipe",
    @"lt",
    @"gt",
    @"gt_gt",
    @"amp_gt",
    @"amp_gt_gt",
    @"fd_lt",
    @"fd_gt",
    @"fd_dup_out",
    @"fd_dup_in",
    @"assign",
    @"name_eq",
    @"indent",
    @"outdent",
    @"comment",
    @"err",
    @"eof",

    // Internal (used by generator)
    @"skip",
};

// =============================================================================
// TOKEN STRUCT (8 bytes)
// =============================================================================

pub const Token = struct {
    pos: u32,         // Byte position in source (4 bytes)
    len: u16,         // Token length in bytes (2 bytes)
    cat: TokenCat,    // Token category (1 byte)
    pre: u8,          // Preceding whitespace count (1 byte)

    comptime {
        std.debug.assert(@sizeOf(Token) == 8);
    }
};

// =============================================================================
// LEXER
// =============================================================================
pub const BaseLexer = struct {
    const Self = @This();

    source: []const u8,
    pos: u32,
    aux: u16 = 0,
    // State variables
    paren: i8,
    brace: i8,
    bracket: i8,

    pub fn init(source: []const u8) Self {
        return .{
            .source = source,
            .pos = 0,
            .paren = 0,
            .brace = 0,
            .bracket = 0,
        };
    }

    /// Get the text slice for a token (zero-copy into source)
    pub fn text(self: *const Self, tok: Token) []const u8 {
        const start: usize = tok.pos;
        const end: usize = @min(start + tok.len, self.source.len);
        if (start >= self.source.len) return "";
        return self.source[start..end];
    }

    /// Reset lexer to beginning
    pub fn reset(self: *Self) void {
        self.pos = 0;
        self.paren = 0;
        self.brace = 0;
        self.bracket = 0;
    }

    /// Peek at current character (0 if at end)
    inline fn peek(self: *const Self) u8 {
        return if (self.pos < self.source.len) self.source[self.pos] else 0;
    }

    /// Peek at character at offset (0 if at end)
    inline fn peekAt(self: *const Self, offset: u32) u8 {
        const p = self.pos + offset;
        return if (p < self.source.len) self.source[p] else 0;
    }

    /// Get next token
    pub fn next(self: *Self) Token {
        return self.matchRules();
    }

    // Character classification flags (generated from grammar patterns)
    const DIGIT: u8 = 1 << 0;
    const LETTER: u8 = 1 << 1;
    const WHITESPACE: u8 = 1 << 2;

    const charFlags: [256]u8 = blk: {
        var table: [256]u8 = [_]u8{0} ** 256;
        for ('0'..'9' + 1) |c| table[c] = DIGIT;
        for ('A'..'Z' + 1) |c| table[c] = LETTER;
        for ('a'..'z' + 1) |c| table[c] = LETTER;
        table['!'] = LETTER;
        table['%'] = LETTER;
        table['*'] = LETTER;
        table['+'] = LETTER;
        table[','] = LETTER;
        table['-'] = LETTER;
        table['.'] = LETTER;
        table['/'] = LETTER;
        table[':'] = LETTER;
        table['?'] = LETTER;
        table['@'] = LETTER;
        table['^'] = LETTER;
        table['_'] = LETTER;
        table['~'] = LETTER;
        table[' '] = WHITESPACE;
        table['\t'] = WHITESPACE;
        break :blk table;
    };

    inline fn isDigit(c: u8) bool {
        return (charFlags[c] & DIGIT) != 0;
    }

    inline fn isLetter(c: u8) bool {
        return (charFlags[c] & LETTER) != 0;
    }

    inline fn isWhitespace(c: u8) bool {
        return (charFlags[c] & WHITESPACE) != 0;
    }

    inline fn isIdentChar(c: u8) bool {
        return isLetter(c) or isDigit(c);
    }
    /// Match lexer rules
    pub fn matchRules(self: *Self) Token {
        // Count whitespace first
        const wsStart = self.pos;
        while (self.pos < self.source.len and isWhitespace(self.source[self.pos])) {
            self.pos += 1;
        }
        const wsCount: u8 = @intCast(@min(self.pos - wsStart, 255));
        // EOF check
        if (self.pos >= self.source.len) {            return Token{ .cat = .@"eof", .pre = wsCount, .pos = self.pos, .len = 0 };
        }

        const start = self.pos;
        const c = self.source[self.pos];
        // Newline handling (generated from grammar rules)
        if (c == '\n' or c == '\r') {
            if (c == '\r' and self.pos + 1 < self.source.len and self.source[self.pos + 1] == '\n') {
                self.pos += 2;
                return Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 2 };
            }
                self.pos += 1;
                return Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 1 };
        }
        if (c == '\'') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '\'') {
                    self.pos += 1;
                    if (self.pos < self.source.len and self.source[self.pos] == '\'') { self.pos += 1; continue; }
                    return Token{ .cat = .@"string_sq", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        if (c == '"') {            self.pos += 1;
            while (self.pos < self.source.len) {
                const ch = self.source[self.pos];
                if (ch == '"') {
                    self.pos += 1;
                    return Token{ .cat = .@"string_dq", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (ch == '\\') { self.pos += 2; continue; }
                if (ch == '\n') break;
                self.pos += 1;
            }
            return Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Number
        if (isDigit(c)) {
            const tok = self.scanNumber(start, wsCount);
            if (tok.cat == .@"integer") {
                if (self.pos + 3 <= self.source.len and self.source[self.pos + 0] == '>' and self.source[self.pos + 1] == '&' and ((self.source[self.pos + 2] >= '0' and self.source[self.pos + 2] <= '9'))) {
                    self.pos += 3;
                    while (self.pos < self.source.len and ((self.source[self.pos] >= '0' and self.source[self.pos] <= '9'))) self.pos += 1;
                    return Token{ .cat = .@"fd_dup_out", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 3 <= self.source.len and self.source[self.pos + 0] == '<' and self.source[self.pos + 1] == '&' and ((self.source[self.pos + 2] >= '0' and self.source[self.pos + 2] <= '9'))) {
                    self.pos += 3;
                    while (self.pos < self.source.len and ((self.source[self.pos] >= '0' and self.source[self.pos] <= '9'))) self.pos += 1;
                    return Token{ .cat = .@"fd_dup_in", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 1 <= self.source.len and self.source[self.pos + 0] == '>') {
                    self.pos += 1;
                    return Token{ .cat = .@"fd_gt", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
                if (self.pos + 1 <= self.source.len and self.source[self.pos + 0] == '<') {
                    self.pos += 1;
                    return Token{ .cat = .@"fd_lt", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
                }
            }
            return tok;
        }
        // Identifier
        if (isLetter(c)) {
            return self.scanIdent(start, wsCount);
        }
        if (c == '$') {
            const nc = if (self.pos + 1 < self.source.len) self.source[self.pos + 1] else 0;
            if (nc == '{') {
                self.pos += 2;
                while (self.pos < self.source.len and self.source[self.pos] != '}' and self.source[self.pos] != '\n') self.pos += 1;
                if (self.pos < self.source.len and self.source[self.pos] == '}') self.pos += 1;
                return Token{ .cat = .@"var_braced", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
            }
            if ((nc >= 'a' and nc <= 'z') or (nc >= 'A' and nc <= 'Z') or nc == '_') {
                self.pos += 1;
                while (self.pos < self.source.len) {
                    const vc = self.source[self.pos];
                    if (!((vc >= 'a' and vc <= 'z') or (vc >= 'A' and vc <= 'Z') or (vc >= '0' and vc <= '9') or vc == '_')) break;
                    self.pos += 1;
                }
                return Token{ .cat = .@"variable", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
            }
            if (nc >= '0' and nc <= '9') {
                self.pos += 2;
                return Token{ .cat = .@"variable", .pre = wsCount, .pos = start, .len = 2 };
            }
        }
        // Comment (scan to end of line)
        if (c == '#') {
            while (self.pos < self.source.len and self.source[self.pos] != '\n') {
                self.pos += 1;
            }
            return Token{ .cat = .@"comment", .pre = wsCount, .pos = start, .len = @intCast(self.pos - start) };
        }
        // Single/multi-char operators
        self.pos += 1;
        return switch (c) {
            '$' => blk: {
                if (self.peek() == '(') {
                    self.pos += 1;
                self.paren += 1;
                    break :blk Token{ .cat = .@"dollar_paren", .pre = wsCount, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '&' => blk: {
                if (self.peek() == '&') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"and_and", .pre = wsCount, .pos = start, .len = 2 };
                }
                if (self.peek() == '>') {
                    self.pos += 1;
                    if (self.peek() == '>') {
                        self.pos += 1;
                    break :blk Token{ .cat = .@"amp_gt_gt", .pre = wsCount, .pos = start, .len = 3 };
                    }
                    break :blk Token{ .cat = .@"amp_gt", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"amp", .pre = wsCount, .pos = start, .len = 1 };
            },
            '(' => blk: {
                self.paren += 1;
                    break :blk Token{ .cat = .@"lparen", .pre = wsCount, .pos = start, .len = 1 };
            },
            ')' => blk: {
                self.paren -= 1;
                    break :blk Token{ .cat = .@"rparen", .pre = wsCount, .pos = start, .len = 1 };
            },
            ';' => Token{ .cat = .@"semi", .pre = wsCount, .pos = start, .len = 1 },
            '<' => Token{ .cat = .@"lt", .pre = wsCount, .pos = start, .len = 1 },
            '=' => Token{ .cat = .@"assign", .pre = wsCount, .pos = start, .len = 1 },
            '>' => blk: {
                if (self.peek() == '>') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"gt_gt", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"gt", .pre = wsCount, .pos = start, .len = 1 };
            },
            '@' => blk: {
                if (self.peek() == '(') {
                    self.pos += 1;
                self.paren += 1;
                    break :blk Token{ .cat = .@"at_paren", .pre = wsCount, .pos = start, .len = 2 };
                }
                self.pos -= 1;
                break :blk Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 };
            },
            '[' => blk: {
                self.bracket += 1;
                    break :blk Token{ .cat = .@"lbracket", .pre = wsCount, .pos = start, .len = 1 };
            },
            ']' => blk: {
                self.bracket -= 1;
                    break :blk Token{ .cat = .@"rbracket", .pre = wsCount, .pos = start, .len = 1 };
            },
            '{' => blk: {
                self.brace += 1;
                    break :blk Token{ .cat = .@"lbrace", .pre = wsCount, .pos = start, .len = 1 };
            },
            '|' => blk: {
                if (self.peek() == '|') {
                    self.pos += 1;
                    break :blk Token{ .cat = .@"or_or", .pre = wsCount, .pos = start, .len = 2 };
                }
                    break :blk Token{ .cat = .@"pipe", .pre = wsCount, .pos = start, .len = 1 };
            },
            '}' => blk: {
                self.brace -= 1;
                    break :blk Token{ .cat = .@"rbrace", .pre = wsCount, .pos = start, .len = 1 };
            },
            else => Token{ .cat = .@"err", .pre = wsCount, .pos = start, .len = 1 },
        };
    }

    /// Scan number (generated from grammar)
    fn scanNumber(self: *Self, start: u32, ws: u8) Token {        // Decimal integer
        if (isDigit(self.source[self.pos])) {
            while (self.pos < self.source.len and isDigit(self.source[self.pos])) {
                self.pos += 1;
            }
        }
        return Token{ .cat = .@"integer", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }

    /// Scan identifier (generated from grammar)
    fn scanIdent(self: *Self, start: u32, ws: u8) Token {
        while (self.pos < self.source.len and isIdentChar(self.source[self.pos])) {
            self.pos += 1;
        }
        return Token{ .cat = .@"ident", .pre = ws, .pos = start, .len = @intCast(self.pos - start) };
    }
};

pub const Lexer = if (@hasDecl(slash, "Lexer")) slash.Lexer else BaseLexer;

// =============================================================================
// Tag Enum (re-exported from language module)
// =============================================================================
pub const Tag = slash.Tag;

// =============================================================================
// S-Expression (AST Node) - 5 Clean Variants
// =============================================================================

pub const Sexp = union(enum) {
    nil:  void,                                        // Empty (nothing)
    tag:  Tag,                                         // Semantic type (1 byte)
    src:  struct { pos: u32, len: u16, id: u16 },      // Source ref + identity (8 bytes)
    str:  []const u8,                                  // Embedded string (16 bytes)
    list: []const Sexp,                                // Compound: (tag child1 ...)

    /// Get token text from source
    pub fn getText(self: Sexp, source: []const u8) []const u8 {
        return switch (self) {
            .src => |s| source[s.pos..][0..s.len],
            .str => |s| s,
            else => "",
        };
    }

    /// Format for debug output
    pub fn write(self: Sexp, source: []const u8, w: anytype) !void {
        switch (self) {
            .nil => try w.writeAll("_"),
            .tag => |t| try w.print("{s}", .{@tagName(t)}),
            .src => |s| try w.print("{s}", .{source[s.pos..][0..s.len]}),
            .str => |s| try w.print("\"{s}\"", .{s}),
            .list => |items| {
                try w.writeAll("(");
                for (items, 0..) |item, i| {
                    if (i > 0) try w.writeAll(" ");
                    try item.write(source, w);
                }
                try w.writeAll(")");
            },
        }
    }
};

// =============================================================================
// Parser
// =============================================================================

pub const Parser = struct {
    arena: std.heap.ArenaAllocator,
    lexer: Lexer,
    source: []const u8,
    current: Token,
    injectedToken: ?u16 = null,
    lastMatchedId: u16 = 0,

    stateStack: std.ArrayListUnmanaged(u16) = .empty,
    valueStack: std.ArrayListUnmanaged(Sexp) = .empty,

    pub fn init(backingAllocator: std.mem.Allocator, source: []const u8) Parser {
        var p = Parser{
            .arena = std.heap.ArenaAllocator.init(backingAllocator),
            .lexer = Lexer.init(source),
            .source = source,
            .current = undefined,
        };
        p.current = p.lexer.next();
        return p;
    }

    pub fn deinit(self: *Parser) void {
        self.arena.deinit();
    }

    fn allocator(self: *Parser) std.mem.Allocator {
        return self.arena.allocator();
    }

    pub fn printError(self: *Parser) void {
        const pos: usize = @min(self.current.pos, self.source.len);
        var line: usize = 1;
        var col: usize = 1;
        var i: usize = 0;
        while (i < pos) : (i += 1) {
            if (self.source[i] == '\n') {
                line += 1;
                col = 1;
            } else {
                col += 1;
            }
        }
        std.debug.print("Parse error at line {d}, column {d}: unexpected {s}\n", .{
            line,
            col,
            @tagName(self.current.cat),
        });
    }

    fn doParse(self: *Parser, startSym: u16) !Sexp {
        const startState = getStartState(startSym);
        self.stateStack.clearRetainingCapacity();
        self.valueStack.clearRetainingCapacity();
        try self.stateStack.append(self.allocator(), startState);

        while (true) {
            const state = self.stateStack.getLast();
            const sym = if (self.injectedToken) |inj| inj else self.tokenToSymbol(self.current);
            var action = getAction(state, sym);

            // X "c" check: if reducing and next char matches with pre==0, shift instead
            if (action < -1 and self.current.pre == 0 and self.current.pos < self.source.len) {
                if (getImmediateShift(state, self.source[self.current.pos])) |shiftTarget| {
                    action = shiftTarget;
                }
            }

            if (action == 0) {
                return error.ParseError;
            } else if (action == -1) {
                return self.valueStack.getLast();
            } else if (action > 0) {
                // Shift
                if (self.injectedToken != null) {
                    try self.valueStack.append(self.allocator(), .nil);
                    self.injectedToken = null;
                } else {
                    try self.valueStack.append(self.allocator(), .{ .src = .{
                        .pos = self.current.pos,
                        .len = self.current.len,
                        .id  = if (self.lastMatchedId != 0) self.lastMatchedId else self.lexer.base.aux,
                    } });
                    self.lastMatchedId = 0;
                    self.lexer.base.aux = 0;
                    self.current = self.lexer.next();
                }
                try self.stateStack.append(self.allocator(), @intCast(action));
            } else {
                // Reduce
                const ruleId: u16 = @intCast(-action - 2);
                var pass: [maxArgs]Sexp = undefined;
                const len = ruleLen[ruleId];
                for (0..len) |i| {
                    pass[len - 1 - i] = self.valueStack.pop().?;
                    _ = self.stateStack.pop();
                }

                const result = self.executeAction(ruleId, pass[0..len]);

                if (isAcceptRule(ruleId)) return result;

                try self.valueStack.append(self.allocator(), result);

                const gotoState = self.stateStack.getLast();
                const next = getAction(gotoState, ruleLhs[ruleId]);
                if (next <= 0) return error.ParseError;
                try self.stateStack.append(self.allocator(), @intCast(next));
            }
        }
    }

    /// Spread list helper: [head, ...tail]
    fn spreadList(self: *Parser, head: Sexp, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        out.append(self.allocator(), head) catch return .nil;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Spread only: [...tail]
    fn spreadOnly(self: *Parser, tail: Sexp) Sexp {
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        if (tail == .list) for (tail.list) |item| out.append(self.allocator(), item) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Default list handler
    fn list(self: *Parser, pass: []Sexp) Sexp {
        if (pass.len == 0) return .nil;
        if (pass.len == 1) return pass[0];
        var out: std.ArrayListUnmanaged(Sexp) = .empty;
        for (pass) |v| out.append(self.allocator(), v) catch return .nil;
        return .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} };
    }

    /// Build S-expression: (tag items...) with trailing nil trimming
    inline fn sexp(self: *Parser, comptime tag: Tag, items: []const Sexp) Sexp {
        if (items.len == 0) {
            const result = self.allocator().alloc(Sexp, 1) catch return .nil;
            result[0] = .{ .tag = tag };
            return .{ .list = result };
        }
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag ...spread) - tag + spread items
    inline fn sexpSpread(self: *Parser, comptime tag: Tag, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const result = self.allocator().alloc(Sexp, len + 1) catch return .nil;
        result[0] = .{ .tag = tag };
        if (len > 0) @memcpy(result[1..][0..len], items[0..len]);
        return .{ .list = result };
    }

    /// Build S-expression: (tag pos ...spread) - tag + position + spread items
    inline fn sexpPosSpread(self: *Parser, comptime tag: Tag, pos: Sexp, spread: Sexp) Sexp {
        const items = if (spread == .list) spread.list else &[_]Sexp{};
        var len = items.len;
        while (len > 0 and items[len - 1] == .nil) len -= 1;
        const skipPos = (pos == .nil and len == 0);
        const total = if (skipPos) 1 else len + 2;
        const result = self.allocator().alloc(Sexp, total) catch return .nil;
        result[0] = .{ .tag = tag };
        if (!skipPos) {
            result[1] = pos;
            if (len > 0) @memcpy(result[2..][0..len], items[0..len]);
        }
        return .{ .list = result };
    }

    fn executeAction(self: *Parser, ruleId: u16, pass: []Sexp) Sexp {
        return switch (ruleId) {
            0 => pass[1],
            1 => self.spreadList(pass[0], pass[1]),
            2 => .{ .list = &[_]Sexp{} },
            3 => self.sexpPosSpread(.@"sequence", pass[0], pass[1]),
            4 => self.list(pass),
            5 => self.list(pass),
            6 => self.list(pass),
            7 => self.list(pass),
            8 => self.list(pass),
            9 => self.list(pass),
            10 => self.sexp(.@"seq_always", &.{pass[1]}),
            11 => self.sexp(.@"seq_always", &.{.nil}),
            12 => self.sexp(.@"seq_and", &.{pass[1]}),
            13 => self.sexp(.@"seq_or", &.{pass[1]}),
            14 => self.sexp(.@"seq_bg", &.{pass[1]}),
            15 => self.sexp(.@"seq_bg", &.{.nil}),
            16 => pass[0],
            17 => self.spreadList(pass[0], pass[1]),
            18 => .{ .list = &[_]Sexp{} },
            19 => self.spreadList(pass[0], pass[1]),
            20 => self.sexpPosSpread(.@"pipeline", pass[0], pass[1]),
            21 => pass[1],
            22 => self.list(pass),
            23 => self.list(pass),
            24 => self.sexp(.@"subshell", &.{pass[1]}),
            25 => self.sexp(.@"subshell", &.{pass[1], pass[3]}),
            26 => self.sexp(.@"block", &.{pass[1]}),
            27 => self.sexp(.@"block", &.{pass[1], pass[3]}),
            28 => self.spreadList(pass[0], pass[1]),
            29 => .{ .list = &[_]Sexp{} },
            30 => self.spreadList(pass[0], pass[1]),
            31 => self.sexpSpread(.@"redirects", pass[0]),
            32 => self.spreadList(pass[0], pass[1]),
            33 => .{ .list = &[_]Sexp{} },
            34 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"command" }) catch break :blk .nil; out.append(self.allocator(), .nil) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; if (pass[1] == .list) for (pass[1].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            35 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; out.append(self.allocator(), .{ .tag = .@"command" }) catch break :blk .nil; out.append(self.allocator(), pass[0]) catch break :blk .nil; out.append(self.allocator(), pass[1]) catch break :blk .nil; if (pass[2] == .list) for (pass[2].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            36 => self.spreadList(pass[0], pass[1]),
            37 => .{ .list = &[_]Sexp{} },
            38 => self.spreadList(pass[0], pass[1]),
            39 => self.sexpSpread(.@"env_binds", pass[0]),
            40 => self.sexpSpread(.@"assigns", pass[0]),
            41 => self.sexp(.@"env_bind", &.{pass[0], pass[1]}),
            42 => self.sexp(.@"scalar", &.{pass[0]}),
            43 => self.sexpSpread(.@"list", pass[1]),
            44 => self.spreadList(pass[0], pass[1]),
            45 => .{ .list = &[_]Sexp{} },
            46 => blk: { var out: std.ArrayListUnmanaged(Sexp) = .empty; if (pass[0] == .list) for (pass[0].list) |item| out.append(self.allocator(), item) catch break :blk .nil; while (out.items.len > 0 and out.items[out.items.len - 1] == .nil) _ = out.pop(); break :blk .{ .list = out.toOwnedSlice(self.allocator()) catch &[_]Sexp{} }; },
            47 => self.list(pass),
            48 => self.list(pass),
            49 => self.sexp(.@"word", &.{pass[0]}),
            50 => self.sexp(.@"word", &.{pass[0]}),
            51 => self.sexp(.@"word", &.{pass[0]}),
            52 => self.sexp(.@"word", &.{pass[0]}),
            53 => self.sexp(.@"var", &.{pass[0]}),
            54 => self.sexp(.@"var_braced", &.{pass[0]}),
            55 => self.sexp(.@"cmd_subst", &.{pass[1]}),
            56 => self.sexp(.@"list_capture", &.{pass[1]}),
            57 => self.list(pass),
            58 => self.sexp(.@"word", &.{pass[0]}),
            59 => self.sexp(.@"word", &.{pass[0]}),
            60 => self.sexp(.@"if", &.{pass[1], pass[2], .nil}),
            61 => self.sexp(.@"if", &.{pass[1], pass[2], pass[3]}),
            62 => pass[0],
            63 => self.sexp(.@"cond_and", &.{pass[0], pass[2]}),
            64 => self.sexp(.@"cond_or", &.{pass[0], pass[2]}),
            65 => self.sexp(.@"else", &.{pass[1]}),
            66 => self.sexp(.@"elif", &.{pass[1]}),
            67 => self.sexp(.@"body", &.{pass[1]}),
            68 => self.sexp(.@"body", &.{pass[1]}),
            69 => self.sexp(.@"while", &.{pass[1], pass[2]}),
            70 => self.sexp(.@"for", &.{pass[1], pass[3], pass[4]}),
            71 => self.spreadList(pass[0], pass[1]),
            72 => self.sexpSpread(.@"words", pass[0]),
            73 => self.sexp(.@"redir_read", &.{pass[1]}),
            74 => self.sexp(.@"redir_read_fd", &.{pass[0], pass[1]}),
            75 => self.sexp(.@"redir_write", &.{pass[1]}),
            76 => self.sexp(.@"redir_write_fd", &.{pass[0], pass[1]}),
            77 => self.sexp(.@"redir_append", &.{pass[1]}),
            78 => self.sexp(.@"redir_both", &.{pass[1]}),
            79 => self.sexp(.@"redir_both_append", &.{pass[1]}),
            80 => self.sexp(.@"redir_dup_out", &.{pass[0]}),
            81 => self.sexp(.@"redir_dup_in", &.{pass[0]}),
            82 => self.list(pass),
            else => .nil,
        };
    }

    fn tokenToSymbol(self: *Parser, token: Token) u16 {
        return switch (token.cat) {
            .@"eof" => 1,
            .@"ident" => self.identToSymbol(token),
            .@"semi" => 31,
            .@"and_and" => 32,
            .@"or_or" => 33,
            .@"amp" => 34,
            .@"pipe" => 37,
            .@"lparen" => 38,
            .@"rparen" => 39,
            .@"lbrace" => 40,
            .@"rbrace" => 41,
            .@"name_eq" => 47,
            .@"lbracket" => 48,
            .@"rbracket" => 49,
            .@"integer" => 52,
            .@"string_sq" => 53,
            .@"string_dq" => 54,
            .@"variable" => 55,
            .@"var_braced" => 56,
            .@"dollar_paren" => 57,
            .@"at_paren" => 58,
            .@"assign" => 59,
            .@"indent" => 62,
            .@"outdent" => 63,
            .@"lt" => 68,
            .@"fd_lt" => 69,
            .@"gt" => 70,
            .@"fd_gt" => 71,
            .@"gt_gt" => 72,
            .@"amp_gt" => 73,
            .@"amp_gt_gt" => 74,
            .@"fd_dup_out" => 75,
            .@"fd_dup_in" => 76,
            else => 2, // error
        };
    }

    fn identToSymbol(self: *Parser, token: Token) u16 {
        const text = self.source[token.pos..][0..token.len];
        if (text.len == 0) return symIdent;
        if (self.tryIdentAsKeyword(token, text)) |sym| return sym;
        return symIdent;
    }

    fn tryIdentAsKeyword(self: *Parser, token: Token, text: []const u8) ?u16 {
        _ = token;
        const state = self.stateStack.getLast();
        if (slash.keywordAs(text)) |id| {
            const idIdx = @intFromEnum(id);
            const sym = keywordToSymbol[idIdx];
            if (sym != 0 and getAction(state, sym) != 0) {
                self.lastMatchedId = @intCast(idIdx);
                return sym;
            }
            const fallback = keywordFallbackSymbol;
            if (fallback != 0 and getAction(state, fallback) != 0) {
                self.lastMatchedId = @intCast(idIdx);
                return fallback;
            }
        }
        return null;
    }

    pub fn parseProgram(self: *Parser) !Sexp {
        self.injectedToken = SYM_program_START;
        return self.doParse(SYM_program);
    }
};

// Symbol IDs
const SYM_program: u16 = 3;
const SYM_program_START: u16 = 77;
const symIdent: u16 = 51;

// Mapping from slash.KeywordId to grammar symbol IDs (computed at comptime)
const keywordToSymbol = blk: {
    var arr: [512]u16 = .{0} ** 512;
    if (@hasField(slash.KeywordId, "SEMI")) arr[@intFromEnum(slash.KeywordId.SEMI)] = 31;
    if (@hasField(slash.KeywordId, "AND_AND")) arr[@intFromEnum(slash.KeywordId.AND_AND)] = 32;
    if (@hasField(slash.KeywordId, "OR_OR")) arr[@intFromEnum(slash.KeywordId.OR_OR)] = 33;
    if (@hasField(slash.KeywordId, "AMP")) arr[@intFromEnum(slash.KeywordId.AMP)] = 34;
    if (@hasField(slash.KeywordId, "PIPE")) arr[@intFromEnum(slash.KeywordId.PIPE)] = 37;
    if (@hasField(slash.KeywordId, "LPAREN")) arr[@intFromEnum(slash.KeywordId.LPAREN)] = 38;
    if (@hasField(slash.KeywordId, "RPAREN")) arr[@intFromEnum(slash.KeywordId.RPAREN)] = 39;
    if (@hasField(slash.KeywordId, "LBRACE")) arr[@intFromEnum(slash.KeywordId.LBRACE)] = 40;
    if (@hasField(slash.KeywordId, "RBRACE")) arr[@intFromEnum(slash.KeywordId.RBRACE)] = 41;
    if (@hasField(slash.KeywordId, "NAME_EQ")) arr[@intFromEnum(slash.KeywordId.NAME_EQ)] = 47;
    if (@hasField(slash.KeywordId, "LBRACKET")) arr[@intFromEnum(slash.KeywordId.LBRACKET)] = 48;
    if (@hasField(slash.KeywordId, "RBRACKET")) arr[@intFromEnum(slash.KeywordId.RBRACKET)] = 49;
    if (@hasField(slash.KeywordId, "IDENT")) arr[@intFromEnum(slash.KeywordId.IDENT)] = 51;
    if (@hasField(slash.KeywordId, "INTEGER")) arr[@intFromEnum(slash.KeywordId.INTEGER)] = 52;
    if (@hasField(slash.KeywordId, "STRING_SQ")) arr[@intFromEnum(slash.KeywordId.STRING_SQ)] = 53;
    if (@hasField(slash.KeywordId, "STRING_DQ")) arr[@intFromEnum(slash.KeywordId.STRING_DQ)] = 54;
    if (@hasField(slash.KeywordId, "VARIABLE")) arr[@intFromEnum(slash.KeywordId.VARIABLE)] = 55;
    if (@hasField(slash.KeywordId, "VAR_BRACED")) arr[@intFromEnum(slash.KeywordId.VAR_BRACED)] = 56;
    if (@hasField(slash.KeywordId, "DOLLAR_PAREN")) arr[@intFromEnum(slash.KeywordId.DOLLAR_PAREN)] = 57;
    if (@hasField(slash.KeywordId, "AT_PAREN")) arr[@intFromEnum(slash.KeywordId.AT_PAREN)] = 58;
    if (@hasField(slash.KeywordId, "ASSIGN")) arr[@intFromEnum(slash.KeywordId.ASSIGN)] = 59;
    if (@hasField(slash.KeywordId, "IF")) arr[@intFromEnum(slash.KeywordId.IF)] = 60;
    if (@hasField(slash.KeywordId, "ELSE")) arr[@intFromEnum(slash.KeywordId.ELSE)] = 61;
    if (@hasField(slash.KeywordId, "INDENT")) arr[@intFromEnum(slash.KeywordId.INDENT)] = 62;
    if (@hasField(slash.KeywordId, "OUTDENT")) arr[@intFromEnum(slash.KeywordId.OUTDENT)] = 63;
    if (@hasField(slash.KeywordId, "WHILE")) arr[@intFromEnum(slash.KeywordId.WHILE)] = 64;
    if (@hasField(slash.KeywordId, "FOR")) arr[@intFromEnum(slash.KeywordId.FOR)] = 65;
    if (@hasField(slash.KeywordId, "IN")) arr[@intFromEnum(slash.KeywordId.IN)] = 66;
    if (@hasField(slash.KeywordId, "LT")) arr[@intFromEnum(slash.KeywordId.LT)] = 68;
    if (@hasField(slash.KeywordId, "FD_LT")) arr[@intFromEnum(slash.KeywordId.FD_LT)] = 69;
    if (@hasField(slash.KeywordId, "GT")) arr[@intFromEnum(slash.KeywordId.GT)] = 70;
    if (@hasField(slash.KeywordId, "FD_GT")) arr[@intFromEnum(slash.KeywordId.FD_GT)] = 71;
    if (@hasField(slash.KeywordId, "GT_GT")) arr[@intFromEnum(slash.KeywordId.GT_GT)] = 72;
    if (@hasField(slash.KeywordId, "AMP_GT")) arr[@intFromEnum(slash.KeywordId.AMP_GT)] = 73;
    if (@hasField(slash.KeywordId, "AMP_GT_GT")) arr[@intFromEnum(slash.KeywordId.AMP_GT_GT)] = 74;
    if (@hasField(slash.KeywordId, "FD_DUP_OUT")) arr[@intFromEnum(slash.KeywordId.FD_DUP_OUT)] = 75;
    if (@hasField(slash.KeywordId, "FD_DUP_IN")) arr[@intFromEnum(slash.KeywordId.FD_DUP_IN)] = 76;
    break :blk arr;
};
const keywordFallbackSymbol: u16 = 0;

const ruleLhs = [_]u16{ 3, 30, 30, 4, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 35, 35, 36, 7, 8, 9, 9, 10, 10, 11, 11, 42, 42, 43, 12, 44, 44, 13, 13, 45, 45, 46, 14, 15, 16, 17, 17, 50, 50, 18, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 22, 22, 23, 23, 23, 24, 24, 25, 25, 26, 27, 67, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 78 };
const ruleLen = [_]u8{ 2, 2, 0, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 2, 0, 2, 2, 2, 1, 1, 3, 4, 3, 4, 2, 0, 2, 1, 2, 0, 2, 3, 2, 0, 2, 1, 1, 2, 1, 3, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 4, 1, 3, 3, 2, 2, 3, 3, 3, 5, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2 };

// Parse Table: 130 states × 79 symbols
const numStates = 130;
const numSymbols = 79;

const sparse = [numStates][]const i16{
    &.{3,1,77,2},
    &.{1,-1},
    &.{4,30,5,22,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{1,-1},
    &.{1,-18,8,33,31,-18,32,-18,33,-18,34,-18,36,35,37,34,39,-18,40,-18,41,-18,62,-18,63,-18},
    &.{7,37,9,4,10,7,13,6,14,19,16,8,20,15,23,38,38,24,46,36,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11},
    &.{1,-24,31,-24,32,-24,33,-24,34,-24,37,-24,39,-24,40,-24,41,-24,62,-24,63,-24},
    &.{1,-25,31,-25,32,-25,33,-25,34,-25,37,-25,39,-25,40,-25,41,-25,62,-25,63,-25},
    &.{1,-39,16,39,31,-39,32,-39,33,-39,34,-39,39,-39,41,-39,45,40,47,31,51,-39,52,-39,53,-39,54,-39,55,-39,56,-39,57,-39,58,-39,63,-39},
    &.{4,41,5,22,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{51,42},
    &.{4,43,5,22,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{7,37,9,4,10,7,13,6,14,19,16,8,20,15,23,44,38,24,46,36,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11},
    &.{1,-51,31,-51,32,-51,33,-51,34,-51,37,-51,39,-51,40,-51,41,-51,47,-51,49,-51,51,-51,52,-51,53,-51,54,-51,55,-51,56,-51,57,-51,58,-51,59,-51,62,-51,63,-51,68,-51,69,-51,70,-51,71,-51,72,-51,73,-51,74,-51,75,-51,76,-51},
    &.{1,-6,31,-6,32,-6,33,-6,34,-6,39,-6,41,-6,63,-6},
    &.{1,-35,19,49,20,53,21,51,29,52,31,-35,32,-35,33,-35,34,-35,37,-35,39,-35,40,-35,41,-35,44,57,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46,62,-35,63,-35,68,55,69,54,70,48,71,47,72,45,73,59,74,58,75,60,76,50},
    &.{1,-56,31,-56,32,-56,33,-56,34,-56,37,-56,39,-56,40,-56,41,-56,47,-56,49,-56,51,-56,52,-56,53,-56,54,-56,55,-56,56,-56,57,-56,58,-56,59,-56,62,-56,63,-56,68,-56,69,-56,70,-56,71,-56,72,-56,73,-56,74,-56,75,-56,76,-56},
    &.{1,-11,31,-11,32,-11,33,-11,34,-11,39,-11,41,-11,63,-11},
    &.{1,-7,31,-7,32,-7,33,-7,34,-7,39,-7,41,-7,63,-7},
    &.{20,61,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11},
    &.{1,-10,31,-10,32,-10,33,-10,34,-10,39,-10,41,-10,63,-10},
    &.{1,-9,31,-9,32,-9,33,-9,34,-9,39,-9,41,-9,63,-9},
    &.{1,-4,6,64,30,65,31,67,32,66,33,63,34,62,39,-4,41,-4,63,-4},
    &.{1,-8,31,-8,32,-8,33,-8,34,-8,39,-8,41,-8,63,-8},
    &.{4,68,5,22,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{1,-53,31,-53,32,-53,33,-53,34,-53,37,-53,39,-53,40,-53,41,-53,47,-53,49,-53,51,-53,52,-53,53,-53,54,-53,55,-53,56,-53,57,-53,58,-53,59,-53,62,-53,63,-53,68,-53,69,-53,70,-53,71,-53,72,-53,73,-53,74,-53,75,-53,76,-53},
    &.{1,-55,31,-55,32,-55,33,-55,34,-55,37,-55,39,-55,40,-55,41,-55,47,-55,49,-55,51,-55,52,-55,53,-55,54,-55,55,-55,56,-55,57,-55,58,-55,59,-55,62,-55,63,-55,68,-55,69,-55,70,-55,71,-55,72,-55,73,-55,74,-55,75,-55,76,-55},
    &.{1,-42,31,-42,32,-42,33,-42,34,-42,39,-42,41,-42,51,-41,52,-41,53,-41,54,-41,55,-41,56,-41,57,-41,58,-41,63,-42},
    &.{4,69,5,22,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{1,-52,31,-52,32,-52,33,-52,34,-52,37,-52,39,-52,40,-52,41,-52,47,-52,49,-52,51,-52,52,-52,53,-52,54,-52,55,-52,56,-52,57,-52,58,-52,59,-52,62,-52,63,-52,68,-52,69,-52,70,-52,71,-52,72,-52,73,-52,74,-52,75,-52,76,-52},
    &.{1,-2},
    &.{17,70,20,53,21,71,47,56,48,72,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{1,-54,31,-54,32,-54,33,-54,34,-54,37,-54,39,-54,40,-54,41,-54,47,-54,49,-54,51,-54,52,-54,53,-54,54,-54,55,-54,56,-54,57,-54,58,-54,59,-54,62,-54,63,-54,68,-54,69,-54,70,-54,71,-54,72,-54,73,-54,74,-54,75,-54,76,-54},
    &.{1,-20,8,73,31,-20,32,-20,33,-20,34,-20,35,74,37,34,39,-20,40,-20,41,-20,62,-20,63,-20},
    &.{9,75,10,7,13,6,14,19,16,8,20,15,38,24,46,36,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11},
    &.{1,-22,31,-22,32,-22,33,-22,34,-22,39,-22,40,-22,41,-22,62,-22,63,-22},
    &.{51,-41,52,-41,53,-41,54,-41,55,-41,56,-41,57,-41,58,-41},
    &.{32,-64,33,-64,40,-64,62,-64},
    &.{25,79,32,76,33,78,40,77,62,80},
    &.{1,-39,16,39,31,-39,32,-39,33,-39,34,-39,39,-39,41,-39,45,81,47,31,51,-39,52,-39,53,-39,54,-39,55,-39,56,-39,57,-39,58,-39,63,-39},
    &.{1,-40,31,-40,32,-40,33,-40,34,-40,39,-40,41,-40,51,-40,52,-40,53,-40,54,-40,55,-40,56,-40,57,-40,58,-40,63,-40},
    &.{39,82},
    &.{66,83},
    &.{39,84},
    &.{25,85,32,76,33,78,40,77,62,80},
    &.{20,53,21,86,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{1,-61,31,-61,32,-61,33,-61,34,-61,37,-61,39,-61,40,-61,41,-61,47,-61,49,-61,51,-61,52,-61,53,-61,54,-61,55,-61,56,-61,57,-61,58,-61,59,-61,62,-61,63,-61,68,-61,69,-61,70,-61,71,-61,72,-61,73,-61,74,-61,75,-61,76,-61},
    &.{20,53,21,87,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{20,53,21,88,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{1,-35,19,49,20,53,21,51,29,52,31,-35,32,-35,33,-35,34,-35,37,-35,39,-35,40,-35,41,-35,44,89,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46,62,-35,63,-35,68,55,69,54,70,48,71,47,72,45,73,59,74,58,75,60,76,50},
    &.{1,-83,31,-83,32,-83,33,-83,34,-83,37,-83,39,-83,40,-83,41,-83,47,-83,51,-83,52,-83,53,-83,54,-83,55,-83,56,-83,57,-83,58,-83,59,-83,62,-83,63,-83,68,-83,69,-83,70,-83,71,-83,72,-83,73,-83,74,-83,75,-83,76,-83},
    &.{1,-49,31,-49,32,-49,33,-49,34,-49,37,-49,39,-49,40,-49,41,-49,47,-49,51,-49,52,-49,53,-49,54,-49,55,-49,56,-49,57,-49,58,-49,59,-49,62,-49,63,-49,68,-49,69,-49,70,-49,71,-49,72,-49,73,-49,74,-49,75,-49,76,-49},
    &.{1,-50,31,-50,32,-50,33,-50,34,-50,37,-50,39,-50,40,-50,41,-50,47,-50,51,-50,52,-50,53,-50,54,-50,55,-50,56,-50,57,-50,58,-50,59,-50,62,-50,63,-50,68,-50,69,-50,70,-50,71,-50,72,-50,73,-50,74,-50,75,-50,76,-50},
    &.{1,-59,31,-59,32,-59,33,-59,34,-59,37,-59,39,-59,40,-59,41,-59,47,-59,49,-59,51,-59,52,-59,53,-59,54,-59,55,-59,56,-59,57,-59,58,-59,59,-59,62,-59,63,-59,68,-59,69,-59,70,-59,71,-59,72,-59,73,-59,74,-59,75,-59,76,-59},
    &.{20,53,21,90,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{20,53,21,91,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{1,-60,31,-60,32,-60,33,-60,34,-60,37,-60,39,-60,40,-60,41,-60,47,-60,49,-60,51,-60,52,-60,53,-60,54,-60,55,-60,56,-60,57,-60,58,-60,59,-60,62,-60,63,-60,68,-60,69,-60,70,-60,71,-60,72,-60,73,-60,74,-60,75,-60,76,-60},
    &.{1,-36,31,-36,32,-36,33,-36,34,-36,37,-36,39,-36,40,-36,41,-36,62,-36,63,-36},
    &.{20,53,21,92,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{20,53,21,93,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{1,-82,31,-82,32,-82,33,-82,34,-82,37,-82,39,-82,40,-82,41,-82,47,-82,51,-82,52,-82,53,-82,54,-82,55,-82,56,-82,57,-82,58,-82,59,-82,62,-82,63,-82,68,-82,69,-82,70,-82,71,-82,72,-82,73,-82,74,-82,75,-82,76,-82},
    &.{1,-35,19,49,20,53,21,51,29,52,31,-35,32,-35,33,-35,34,-35,37,-35,39,-35,40,-35,41,-35,44,94,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46,62,-35,63,-35,68,55,69,54,70,48,71,47,72,45,73,59,74,58,75,60,76,50},
    &.{1,-17,5,95,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,31,-17,32,-17,33,-17,34,-17,38,24,39,-17,40,28,41,-17,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,63,-17,64,5,65,10},
    &.{5,96,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{1,-4,6,64,30,97,31,67,32,66,33,63,34,62,39,-4,41,-4,63,-4},
    &.{1,-5,39,-5,41,-5,63,-5},
    &.{5,98,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{1,-13,5,99,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,31,-13,32,-13,33,-13,34,-13,38,24,39,-13,40,28,41,-13,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,63,-13,64,5,65,10},
    &.{39,100},
    &.{41,101},
    &.{1,-43,31,-43,32,-43,33,-43,34,-43,39,-43,41,-43,47,-43,51,-43,52,-43,53,-43,54,-43,55,-43,56,-43,57,-43,58,-43,63,-43},
    &.{1,-44,31,-44,32,-44,33,-44,34,-44,39,-44,41,-44,47,-44,51,-44,52,-44,53,-44,54,-44,55,-44,56,-44,57,-44,58,-44,63,-44},
    &.{18,104,20,53,21,103,47,56,49,-47,50,102,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46},
    &.{1,-20,8,73,31,-20,32,-20,33,-20,34,-20,35,105,37,34,39,-20,40,-20,41,-20,62,-20,63,-20},
    &.{1,-21,31,-21,32,-21,33,-21,34,-21,39,-21,40,-21,41,-21,62,-21,63,-21},
    &.{1,-23,31,-23,32,-23,33,-23,34,-23,37,-23,39,-23,40,-23,41,-23,62,-23,63,-23},
    &.{7,106,9,4,10,7,13,6,14,19,16,8,20,15,38,24,46,36,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11},
    &.{4,107,5,22,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{7,108,9,4,10,7,13,6,14,19,16,8,20,15,38,24,46,36,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11},
    &.{1,-71,31,-71,32,-71,33,-71,34,-71,39,-71,41,-71,63,-71},
    &.{4,109,5,22,7,14,9,4,10,7,11,20,13,6,14,19,15,17,16,8,20,15,22,18,26,23,27,21,38,24,40,28,46,27,47,31,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,60,12,64,5,65,10},
    &.{1,-38,31,-38,32,-38,33,-38,34,-38,39,-38,41,-38,51,-38,52,-38,53,-38,54,-38,55,-38,56,-38,57,-38,58,-38,63,-38},
    &.{1,-57,31,-57,32,-57,33,-57,34,-57,37,-57,39,-57,40,-57,41,-57,47,-57,49,-57,51,-57,52,-57,53,-57,54,-57,55,-57,56,-57,57,-57,58,-57,59,-57,62,-57,63,-57,68,-57,69,-57,70,-57,71,-57,72,-57,73,-57,74,-57,75,-57,76,-57},
    &.{20,53,21,112,28,110,47,56,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46,67,111},
    &.{1,-58,31,-58,32,-58,33,-58,34,-58,37,-58,39,-58,40,-58,41,-58,47,-58,49,-58,51,-58,52,-58,53,-58,54,-58,55,-58,56,-58,57,-58,58,-58,59,-58,62,-58,63,-58,68,-58,69,-58,70,-58,71,-58,72,-58,73,-58,74,-58,75,-58,76,-58},
    &.{1,-62,24,113,31,-62,32,-62,33,-62,34,-62,39,-62,41,-62,61,114,63,-62},
    &.{1,-79,31,-79,32,-79,33,-79,34,-79,37,-79,39,-79,40,-79,41,-79,47,-79,51,-79,52,-79,53,-79,54,-79,55,-79,56,-79,57,-79,58,-79,59,-79,62,-79,63,-79,68,-79,69,-79,70,-79,71,-79,72,-79,73,-79,74,-79,75,-79,76,-79},
    &.{1,-78,31,-78,32,-78,33,-78,34,-78,37,-78,39,-78,40,-78,41,-78,47,-78,51,-78,52,-78,53,-78,54,-78,55,-78,56,-78,57,-78,58,-78,59,-78,62,-78,63,-78,68,-78,69,-78,70,-78,71,-78,72,-78,73,-78,74,-78,75,-78,76,-78},
    &.{1,-77,31,-77,32,-77,33,-77,34,-77,37,-77,39,-77,40,-77,41,-77,47,-77,51,-77,52,-77,53,-77,54,-77,55,-77,56,-77,57,-77,58,-77,59,-77,62,-77,63,-77,68,-77,69,-77,70,-77,71,-77,72,-77,73,-77,74,-77,75,-77,76,-77},
    &.{1,-34,31,-34,32,-34,33,-34,34,-34,37,-34,39,-34,40,-34,41,-34,62,-34,63,-34},
    &.{1,-76,31,-76,32,-76,33,-76,34,-76,37,-76,39,-76,40,-76,41,-76,47,-76,51,-76,52,-76,53,-76,54,-76,55,-76,56,-76,57,-76,58,-76,59,-76,62,-76,63,-76,68,-76,69,-76,70,-76,71,-76,72,-76,73,-76,74,-76,75,-76,76,-76},
    &.{1,-75,31,-75,32,-75,33,-75,34,-75,37,-75,39,-75,40,-75,41,-75,47,-75,51,-75,52,-75,53,-75,54,-75,55,-75,56,-75,57,-75,58,-75,59,-75,62,-75,63,-75,68,-75,69,-75,70,-75,71,-75,72,-75,73,-75,74,-75,75,-75,76,-75},
    &.{1,-81,31,-81,32,-81,33,-81,34,-81,37,-81,39,-81,40,-81,41,-81,47,-81,51,-81,52,-81,53,-81,54,-81,55,-81,56,-81,57,-81,58,-81,59,-81,62,-81,63,-81,68,-81,69,-81,70,-81,71,-81,72,-81,73,-81,74,-81,75,-81,76,-81},
    &.{1,-80,31,-80,32,-80,33,-80,34,-80,37,-80,39,-80,40,-80,41,-80,47,-80,51,-80,52,-80,53,-80,54,-80,55,-80,56,-80,57,-80,58,-80,59,-80,62,-80,63,-80,68,-80,69,-80,70,-80,71,-80,72,-80,73,-80,74,-80,75,-80,76,-80},
    &.{1,-37,31,-37,32,-37,33,-37,34,-37,37,-37,39,-37,40,-37,41,-37,62,-37,63,-37},
    &.{1,-16,31,-16,32,-16,33,-16,34,-16,39,-16,41,-16,63,-16},
    &.{1,-15,31,-15,32,-15,33,-15,34,-15,39,-15,41,-15,63,-15},
    &.{1,-3,39,-3,41,-3,63,-3},
    &.{1,-14,31,-14,32,-14,33,-14,34,-14,39,-14,41,-14,63,-14},
    &.{1,-12,31,-12,32,-12,33,-12,34,-12,39,-12,41,-12,63,-12},
    &.{1,-26,12,116,29,115,31,-26,32,-26,33,-26,34,-26,37,-26,39,-26,40,-26,41,-26,43,117,62,-26,63,-26,68,55,69,54,70,48,71,47,72,45,73,59,74,58,75,60,76,50},
    &.{1,-28,12,118,29,115,31,-28,32,-28,33,-28,34,-28,39,-28,41,-28,43,117,63,-28,68,55,69,54,70,48,71,47,72,45,73,59,74,58,75,60,76,50},
    &.{49,-48},
    &.{20,53,21,103,40,-47,47,56,49,-47,50,119,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46,62,-47},
    &.{49,120},
    &.{1,-19,31,-19,32,-19,33,-19,34,-19,39,-19,40,-19,41,-19,62,-19,63,-19},
    &.{32,-65,33,-65,40,-65,62,-65},
    &.{41,121},
    &.{32,-66,33,-66,40,-66,62,-66},
    &.{63,122},
    &.{25,123,40,77,62,80},
    &.{40,-74,62,-74},
    &.{20,53,21,103,40,-47,47,56,50,124,51,13,52,29,53,25,54,32,55,26,56,16,57,9,58,11,59,46,62,-47},
    &.{1,-63,31,-63,32,-63,33,-63,34,-63,39,-63,41,-63,63,-63},
    &.{22,126,25,125,40,77,60,12,62,80},
    &.{1,-31,29,127,31,-31,32,-31,33,-31,34,-31,37,-31,39,-31,40,-31,41,-31,42,128,62,-31,63,-31,68,55,69,54,70,48,71,47,72,45,73,59,74,58,75,60,76,50},
    &.{1,-27,31,-27,32,-27,33,-27,34,-27,37,-27,39,-27,40,-27,41,-27,62,-27,63,-27},
    &.{1,-33,31,-33,32,-33,33,-33,34,-33,37,-33,39,-33,40,-33,41,-33,62,-33,63,-33},
    &.{1,-29,31,-29,32,-29,33,-29,34,-29,39,-29,41,-29,63,-29},
    &.{40,-46,49,-46,62,-46},
    &.{1,-45,31,-45,32,-45,33,-45,34,-45,39,-45,41,-45,47,-45,51,-45,52,-45,53,-45,54,-45,55,-45,56,-45,57,-45,58,-45,63,-45},
    &.{1,-69,31,-69,32,-69,33,-69,34,-69,39,-69,41,-69,61,-69,63,-69},
    &.{1,-70,31,-70,32,-70,33,-70,34,-70,39,-70,41,-70,61,-70,63,-70},
    &.{1,-72,31,-72,32,-72,33,-72,34,-72,39,-72,41,-72,63,-72},
    &.{40,-73,62,-73},
    &.{1,-67,31,-67,32,-67,33,-67,34,-67,39,-67,41,-67,63,-67},
    &.{1,-68,31,-68,32,-68,33,-68,34,-68,39,-68,41,-68,63,-68},
    &.{1,-31,29,127,31,-31,32,-31,33,-31,34,-31,37,-31,39,-31,40,-31,41,-31,42,129,62,-31,63,-31,68,55,69,54,70,48,71,47,72,45,73,59,74,58,75,60,76,50},
    &.{1,-32,31,-32,32,-32,33,-32,34,-32,37,-32,39,-32,40,-32,41,-32,62,-32,63,-32},
    &.{1,-30,31,-30,32,-30,33,-30,34,-30,37,-30,39,-30,40,-30,41,-30,62,-30,63,-30},
};

const parseTable = blk: {
    @setEvalBranchQuota(100000);
    var t: [numStates][numSymbols]i16 = .{.{0} ** numSymbols} ** numStates;
    for (sparse, 0..) |row, state| {
        var i: usize = 0;
        while (i < row.len) : (i += 2) {
            t[state][@intCast(row[i])] = row[i + 1];
        }
    }
    break :blk t;
};

fn getAction(state: u16, sym: u16) i16 {
    return parseTable[state][sym];
}
// X "c" excludes: shift instead of reduce when pre==0 and char matches
const xExcludes = [_]struct { state: u16, char: u8, shift: u16 }{
};

fn getImmediateShift(state: u16, char: u8) ?i16 {
    for (xExcludes) |x| {
        if (x.state == state and x.char == char) return @intCast(x.shift);
    }
    return null;
}
const startStates = [_]struct { sym: u16, state: u16 }{
    .{ .sym = 3, .state = 0 },
};

fn getStartState(startSym: u16) u16 {
    for (startStates) |entry| {
        if (entry.sym == startSym) return entry.state;
    }
    return 0;
}

const acceptRules = [_]u16{ 82 };

fn isAcceptRule(ruleId: u16) bool {
    for (acceptRules) |ar| if (ruleId == ar) return true;
    return false;
}
